"use client";
import { recordDeadline, dateLabel, evidenceBank, type TrackedRecord } from "@/lib/domain";
import { applicationPreparation } from "@/lib/application-preparation";
import { lifecycleLabel } from "@/lib/lifecycle";
import { useWorkspace } from "./workspace-context";
export function ApplicationOverview({record,onDeadline,onTask}:{record:TrackedRecord;onDeadline:()=>void;onTask:()=>void}){
 const {data,updateRecord}=useWorkspace(),preparation=applicationPreparation(record,evidenceBank(data.experiences));
 const update=(patch:Partial<TrackedRecord>)=>updateRecord(record.opportunity.id,patch);
 return (<div className="application-overview"><p className="preparation-status" role="status">{preparation.label}</p>{record.eventDate&&<p><strong>Interview / event:</strong> {dateLabel(record.eventDate)} · Student-entered date</p>}<p><strong>Stage:</strong> {lifecycleLabel(record)} · <strong>Due:</strong> {recordDeadline(record)?dateLabel(recordDeadline(record)):record.opportunity.deadline} · {record.deadlineOverride?"Student-entered date":"Provider source — check current details"}</p><p><strong>Needs doing:</strong> {record.nextAction||record.requirements.find(r=>!r.done)?.label||record.questions.find(q=>q.status==="Draft")?.question||"Check the provider requirements and choose your next action"}</p><p><strong>Outstanding:</strong> {record.requirements.filter(r=>!r.done).length} confirmed requirements · {record.questions.filter(q=>q.status==="Draft").length} draft answers</p><div className="detail-actions"><button className="button secondary" onClick={onDeadline}>Add / change deadline</button><button className="button secondary" onClick={onTask}>Add a task or reminder</button></div><ul className="task-list">{record.requirements.filter(r=>!r.done).slice(0,3).map(r=><li key={r.id}><label><input type="checkbox" checked={r.done} onChange={()=>update({requirements:record.requirements.map(t=>t.id===r.id?{...t,done:true}:t)})}/>Complete: {r.label}</label></li>)}</ul></div>);
}
