"use client";
import { useEffect, useId, useRef, useState } from "react";
import { applicationStages, questionSchema, evidenceBank, type TrackedRecord, type ApplicationQuestion } from "@/lib/domain";
import { lifecycleLabel } from "@/lib/lifecycle";
import { questionCount, evidenceText, evidenceKey } from "@/lib/intelligence";
import { useWorkspace } from "./workspace-context";
import { Field, Empty, download } from "./shared";
import { RequirementManager } from "./requirement-manager";
import { EvidenceSuggestions } from "./evidence-suggestions";
import { evidenceIssues, linkEvidence, questionValidity } from "@/lib/application-preparation";
export function ApplicationWorkspace({record}:{record:TrackedRecord}){
 const {data,updateRecord,toast,navigate,setActiveExperience,activeQuestion,setActiveQuestion,recordMetric}=useWorkspace();
 const [newQuestion,setNewQuestion]=useState(""),[selected,setSelected]=useState(record.questions.some(q=>q.id===activeQuestion)?activeQuestion:record.questions[0]?.id||""),[error,setError]=useState("");
 const question=record.questions.find(q=>q.id===selected),bank=evidenceBank(data.experiences);
 const draftInput=useRef<HTMLTextAreaElement>(null);
 const countId=useId();const sourceIssues=question?evidenceIssues(question,bank):[];
 useEffect(()=>{setSelected(record.questions.some(q=>q.id===activeQuestion)?activeQuestion:record.questions[0]?.id||"");},[activeQuestion,record.opportunity.id]);
 function selectQuestion(id:string){setSelected(id);setActiveQuestion(id);setError("");}
 const update=(patch:Partial<TrackedRecord>)=>updateRecord(record.opportunity.id,patch);
 function patchQuestion(patch:Partial<ApplicationQuestion>){
  if(!question)return;const next={...question,...patch};
  const invalid=questionValidity(next);if(next.status!=="Draft"&&invalid.length){setError(invalid[0]);return;}
  setError("");update({questions:record.questions.map(q=>q.id===question.id?next:q)});
 }
 function copy(e:typeof bank[number],star=false){
  if(!question)return;const draft=[question.draft.trim(),evidenceText(e,star)].filter(Boolean).join("\n\n");
  if(draft.length>20000){setError("This draft is full. Shorten it before adding more evidence.");return;}
  patchQuestion({draft,status:"Draft",...linkEvidence(question,e)});recordMetric("reuse");toast(star?"Recorded details copied into a STAR scaffold. Complete missing details yourself.":"Recorded evidence appended to your draft.");draftInput.current?.focus();
 }
 const done=record.requirements.filter(r=>r.done).length,ready=record.questions.filter(q=>q.status!=="Draft"&&!questionValidity(q).length).length;
 return <section className="application-workspace" aria-label="Application preparation">
 <div className="section-header"><div><h2>Prepare your application</h2><p>Confirm requirements, draft responses and draw on your own experience.</p></div></div>
 <div className="progress-facts"><span>{done} / {record.requirements.length} confirmed tasks complete</span><span>{ready} / {record.questions.length} responses ready</span><span>Status: {lifecycleLabel(record)}</span></div>
 <RequirementManager record={record}/>
 <details className="workspace-section"><summary>Application progress</summary><p className="fine-print">Record milestones only after you do them. Submission and outcomes come from your application status above.</p><ul className="task-list">{applicationStages.map(stage=><li key={stage}><label><input type="checkbox" checked={record.applicationSteps.includes(stage)} onChange={e=>update({applicationSteps:e.target.checked?[...new Set([...record.applicationSteps,stage])]:record.applicationSteps.filter(s=>s!==stage)})}/><span>{stage}</span></label>{record.applicationSteps.includes(stage)&&<Field label={"Milestone date: "+stage}><input className="text-input" type="date" value={record.milestoneDates.find(m=>m.stage===stage)?.date||""} onChange={e=>update({milestoneDates:[...record.milestoneDates.filter(m=>m.stage!==stage),{stage,date:e.target.value}]})}/></Field>}</li>)}</ul><p className="card-intro">{record.applicationSteps.length} recorded milestones. {["Applied","Interview / next stage","Accepted","Unsuccessful","Completed"].includes(record.status)?"Application status: "+lifecycleLabel(record):"Not recorded as submitted."}</p></details>
 <details className="workspace-section" open><summary>Application questions & interview preparation</summary>
 <details className="workspace-section" open={!record.questions.length}><summary>{record.questions.length?"Add another question":"Add your first question"}</summary><form onSubmit={e=>{e.preventDefault();if(!newQuestion.trim()||record.questions.length>=40)return;const value=questionSchema.parse({id:crypto.randomUUID(),question:newQuestion.trim()});update({questions:[...record.questions,value]});selectQuestion(value.id);setNewQuestion("");}}><Field label="New application question"><textarea className="large-textarea mini-textarea" maxLength={1500} value={newQuestion} onChange={e=>setNewQuestion(e.target.value)} placeholder="Paste the provider's exact question…"/></Field><button className="button secondary" disabled={!newQuestion.trim()||record.questions.length>=40}>Add question</button></form></details>
 {!record.questions.length?<Empty title="Give each answer its own space.">Add a provider's question to draft a response and find relevant examples in your Evidence Bank.</Empty>:<>
 {activeQuestion&&!record.questions.some(q=>q.id===activeQuestion)&&<p className="error-message" role="alert">This question is no longer in the application. <button className="inline-link" onClick={()=>selectQuestion(record.questions[0]?.id||"")}>Open an existing question</button></p>}<Field label="Select question"><select className="text-input" value={selected} onChange={e=>{selectQuestion(e.target.value);}}><option value="">Choose a question</option>{record.questions.map(q=><option key={q.id} value={q.id}>{q.question.slice(0,100)} · {q.status}</option>)}</select></Field>
 {question&&<div className="question-editor" key={question.id}><div className="question-heading"><h3>{question.question}</h3><span className="status-chip">{question.status}</span></div><p className="fine-print">Limit: {question.limitKind==="None"||!question.limit?"Not stated":question.limit+" "+question.limitKind.toLowerCase()}</p>{sourceIssues.map(issue=><p className="error-message" role="alert" key={issue.id}>{issue.message}</p>)}<details className="workspace-section"><summary>Edit question text</summary><Field label="Question text"><textarea className="large-textarea mini-textarea" maxLength={1500} value={question.question} onChange={e=>patchQuestion({question:e.target.value||" "})}/></Field></details><details className="workspace-section"><summary>Answer settings & limits</summary><div className="form-grid"><Field label="Response purpose"><select className="text-input" value={question.purpose} onChange={e=>patchQuestion({purpose:e.target.value as ApplicationQuestion["purpose"]})}><option>Application</option><option>Interview</option></select></Field><Field label="Limit type"><select className="text-input" value={question.limitKind} onChange={e=>patchQuestion({limitKind:e.target.value as ApplicationQuestion["limitKind"],status:"Draft"})}><option>None</option><option>Words</option><option>Characters</option></select></Field>{question.limitKind!=="None"&&<Field label="Response limit"><input className="text-input" type="number" min={0} max={20000} value={question.limit} onChange={e=>patchQuestion({limit:Math.max(0,Math.min(20000,Number(e.target.value)||0)),status:"Draft"})}/></Field>}</div></details>
 <Field label="Draft response" hint="Your draft stays in this browser. Suggestions append your recorded example; adapt it to answer the question."><textarea ref={draftInput} className="large-textarea" aria-label="Draft response" aria-describedby={countId} maxLength={20000} value={question.draft} onChange={e=>patchQuestion({draft:e.target.value,status:"Draft",evidenceReviewed:false})}/></Field><p id={countId} className={"draft-count "+(question.limit>0&&question.limitKind!=="None"&&questionCount(question)>question.limit?"danger":"")} role="status">{question.limitKind==="Words"?questionCount(question)+" words":[...question.draft].length+" characters"}{question.limitKind!=="None"&&question.limit>0?" / "+question.limit+" "+question.limitKind.toLowerCase():""}{question.limit>0&&question.limitKind!=="None"&&questionCount(question)>question.limit?" · Over the stated limit":""}</p>
 {question.evidenceIds.length>0&&<label className="review-confirmation"><input type="checkbox" checked={question.evidenceReviewed} onChange={e=>patchQuestion({evidenceReviewed:e.target.checked,status:"Draft"})}/>I have reviewed and adapted this evidence to answer the question</label>}<Field label="Response completion"><select className="text-input compact-select" value={question.status} onChange={e=>patchQuestion({status:e.target.value as ApplicationQuestion["status"]})}><option>Draft</option><option>Ready</option><option>Submitted</option></select></Field><details className="workspace-section"><summary>Notes for this answer</summary><Field label="Question notes"><textarea className="large-textarea mini-textarea" maxLength={2000} value={question.notes} onChange={e=>patchQuestion({notes:e.target.value})}/></Field></details>
 {error&&<p className="error-message" role="alert">{error}</p>}
 <EvidenceSuggestions record={record} question={question} bank={bank} onCopy={copy}/>
 {question.evidenceIds.length>0&&<details className="workspace-section"><summary>Evidence used in this draft</summary>{question.evidenceIds.map(id=>{const e=bank.find(v=>evidenceKey(v)===id);return <p key={id}>{e?<><span>{e.experienceName+" — "+e.skill}</span> <button className="inline-link" onClick={()=>{setActiveExperience(e.experienceId);navigate("reflect");}}>Open original experience</button></>:"Source evidence was removed. Review any copied text before using this answer."}</p>;})}<p className="fine-print">Copied text is a snapshot. Editing the source does not silently change your answer.</p></details>}
 <div className="detail-actions"><button className="button secondary" onClick={()=>download("sixthstep-answer.txt",question.question+"\n\n"+question.draft+"\n\nNotes: "+question.notes+"\nEvidence references: "+question.evidenceIds.join(", "))}>Export answer</button><button className="button text-button danger" onClick={()=>{if(window.confirm("Delete this question and its draft?")){update({questions:record.questions.filter(q=>q.id!==question.id)});selectQuestion("");}}}>Remove question</button></div></div>}</>}
 </details></section>;
}
