"use client";
import { useState } from "react";
import { applicationStages, questionSchema, evidenceBank, type TrackedRecord, type ApplicationQuestion } from "@/lib/domain";
import { requirementOptions, questionCount, suggestEvidence, evidenceText, evidenceKey, starComplete } from "@/lib/intelligence";
import { useWorkspace } from "./workspace-context";
import { Field, Notice, Empty, download } from "./shared";
export function ApplicationWorkspace({record}:{record:TrackedRecord}){
 const {data,updateRecord,toast,navigate,setActiveExperience,activeQuestion}=useWorkspace();
 const [requirement,setRequirement]=useState(requirementOptions[0]),[custom,setCustom]=useState(""),[newQuestion,setNewQuestion]=useState(""),[selected,setSelected]=useState(record.questions.some(q=>q.id===activeQuestion)?activeQuestion:record.questions[0]?.id||""),[error,setError]=useState("");
 const question=record.questions.find(q=>q.id===selected),bank=evidenceBank(data.experiences);
 const suggestions=question?suggestEvidence(question.question,bank):[];
 const update=(patch:Partial<TrackedRecord>)=>updateRecord(record.opportunity.id,patch);
 function patchQuestion(patch:Partial<ApplicationQuestion>){
  if(!question)return;const next={...question,...patch};
  if(next.status!=="Draft"&&(!next.draft.trim()||next.limit>0&&next.limitKind!=="None"&&questionCount(next)>next.limit)){setError("Add a draft within its stated limit before marking it ready or submitted.");return;}
  setError("");update({questions:record.questions.map(q=>q.id===question.id?next:q)});
 }
 function addRequirement(label:string){if(!label.trim()||record.requirements.length>=40)return;if(record.requirements.some(r=>r.label.toLowerCase()===label.trim().toLowerCase())){toast("That requirement is already recorded");return;}update({requirements:[...record.requirements,{id:crypto.randomUUID(),label:label.trim(),note:"",done:false}]});setCustom("");}
 function copy(e:typeof bank[number],star=false){
  if(!question)return;const draft=[question.draft.trim(),evidenceText(e,star)].filter(Boolean).join("\n\n");
  if(draft.length>20000){setError("This draft is full. Shorten it before adding more evidence.");return;}
  patchQuestion({draft,status:"Draft",evidenceIds:[...new Set([...question.evidenceIds,evidenceKey(e)])].slice(0,60)});toast(star?"Recorded details copied into a STAR scaffold. Complete missing details yourself.":"Recorded evidence appended to your draft.");
 }
 const done=record.requirements.filter(r=>r.done).length,ready=record.questions.filter(q=>q.status!=="Draft").length;
 return <section className="application-workspace" aria-label="Application preparation">
 <div className="section-header"><div><h2>Prepare your application</h2><p>Confirm requirements, draft responses and draw on your own experience.</p></div></div>
 <div className="progress-facts"><span>{done} / {record.requirements.length} confirmed tasks complete</span><span>{ready} / {record.questions.length} responses ready</span><span>Status: {record.status}</span></div>
 <details className="workspace-section"><summary>Application requirements</summary><Notice>Nothing is assumed. Add only requirements you have confirmed with the provider. “Complete” means you have dealt with that item.</Notice>
 <div className="form-grid"><Field label="Confirmed requirement"><select className="text-input" value={requirement} onChange={e=>setRequirement(e.target.value)}>{requirementOptions.map(r=><option key={r}>{r}</option>)}</select></Field><div className="field-cta"><button className="button secondary" disabled={record.requirements.length>=40} onClick={()=>addRequirement(requirement)}>Add confirmed requirement</button></div></div>
 <form className="requirement-form" onSubmit={e=>{e.preventDefault();addRequirement(custom);}}><Field label="Other confirmed requirement"><input className="text-input" maxLength={250} value={custom} onChange={e=>setCustom(e.target.value)}/></Field><button className="button secondary" disabled={!custom.trim()||record.requirements.length>=40}>Add requirement</button></form>
 <ul className="task-list">{record.requirements.map(r=><li key={r.id}><div className="requirement-row"><label><input type="checkbox" checked={r.done} onChange={()=>update({requirements:record.requirements.map(v=>v.id===r.id?{...v,done:!v.done}:v)})}/><span>{r.label}</span></label><Field label={"Requirement notes: "+r.label}><input className="text-input" maxLength={1000} value={r.note} onChange={e=>update({requirements:record.requirements.map(v=>v.id===r.id?{...v,note:e.target.value}:v)})}/></Field></div><button className="icon-button" aria-label={"Remove requirement "+r.label} onClick={()=>update({requirements:record.requirements.filter(v=>v.id!==r.id)})}>×</button></li>)}</ul></details>
 <details className="workspace-section"><summary>Application progress</summary><p className="fine-print">Record milestones only after you do them. Submission and outcomes come from your application status above.</p><ul className="task-list">{applicationStages.map(stage=><li key={stage}><label><input type="checkbox" checked={record.applicationSteps.includes(stage)} onChange={e=>update({applicationSteps:e.target.checked?[...new Set([...record.applicationSteps,stage])]:record.applicationSteps.filter(s=>s!==stage)})}/><span>{stage}</span></label>{record.applicationSteps.includes(stage)&&<Field label={"Milestone date: "+stage}><input className="text-input" type="date" value={record.milestoneDates.find(m=>m.stage===stage)?.date||""} onChange={e=>update({milestoneDates:[...record.milestoneDates.filter(m=>m.stage!==stage),{stage,date:e.target.value}]})}/></Field>}</li>)}</ul><p className="card-intro">{record.applicationSteps.length} recorded milestones. {["Applied","Interview / next stage","Accepted","Unsuccessful","Completed"].includes(record.status)?"Application status: "+record.status:"Not recorded as submitted."}</p></details>
 <details className="workspace-section" open><summary>Application questions & interview preparation</summary>
 <details className="workspace-section" open={!record.questions.length}><summary>{record.questions.length?"Add another question":"Add your first question"}</summary><form onSubmit={e=>{e.preventDefault();if(!newQuestion.trim()||record.questions.length>=40)return;const value=questionSchema.parse({id:crypto.randomUUID(),question:newQuestion.trim()});update({questions:[...record.questions,value]});setSelected(value.id);setNewQuestion("");}}><Field label="New application question"><textarea className="large-textarea mini-textarea" maxLength={1500} value={newQuestion} onChange={e=>setNewQuestion(e.target.value)} placeholder="Paste the provider's exact question…"/></Field><button className="button secondary" disabled={!newQuestion.trim()||record.questions.length>=40}>Add question</button></form></details>
 {!record.questions.length?<Empty title="Give each answer its own space.">Add a provider's question to draft a response and find relevant examples in your Evidence Bank.</Empty>:<>
 <Field label="Select question"><select className="text-input" value={selected} onChange={e=>{setSelected(e.target.value);setError("");}}><option value="">Choose a question</option>{record.questions.map(q=><option key={q.id} value={q.id}>{q.question.slice(0,100)} · {q.status}</option>)}</select></Field>
 {question&&<div className="question-editor" key={question.id}><h3>{question.question}</h3><details className="workspace-section"><summary>Edit question text</summary><Field label="Question text"><textarea className="large-textarea mini-textarea" maxLength={1500} value={question.question} onChange={e=>patchQuestion({question:e.target.value||" "})}/></Field></details><details className="workspace-section"><summary>Answer settings & limits</summary><div className="form-grid"><Field label="Response purpose"><select className="text-input" value={question.purpose} onChange={e=>patchQuestion({purpose:e.target.value as ApplicationQuestion["purpose"]})}><option>Application</option><option>Interview</option></select></Field><Field label="Limit type"><select className="text-input" value={question.limitKind} onChange={e=>patchQuestion({limitKind:e.target.value as ApplicationQuestion["limitKind"],status:"Draft"})}><option>None</option><option>Words</option><option>Characters</option></select></Field>{question.limitKind!=="None"&&<Field label="Response limit"><input className="text-input" type="number" min={0} max={20000} value={question.limit} onChange={e=>patchQuestion({limit:Math.max(0,Math.min(20000,Number(e.target.value)||0)),status:"Draft"})}/></Field>}</div></details>
 <Field label="Draft response" hint="Your draft stays in this browser. Suggestions append your recorded example; adapt it to answer the question."><textarea className="large-textarea" maxLength={20000} value={question.draft} onChange={e=>patchQuestion({draft:e.target.value,status:"Draft"})}/></Field><p className={"draft-count "+(question.limit>0&&question.limitKind!=="None"&&questionCount(question)>question.limit?"danger":"")} role="status">{question.limitKind==="Words"?questionCount(question)+" words":[...question.draft].length+" characters"}{question.limitKind!=="None"&&question.limit>0?" / "+question.limit+" "+question.limitKind.toLowerCase():""}{question.limit>0&&question.limitKind!=="None"&&questionCount(question)>question.limit?" · Over the stated limit":""}</p>
 <Field label="Response completion"><select className="text-input compact-select" value={question.status} onChange={e=>patchQuestion({status:e.target.value as ApplicationQuestion["status"]})}><option>Draft</option><option>Ready</option><option>Submitted</option></select></Field><details className="workspace-section"><summary>Notes for this answer</summary><Field label="Question notes"><textarea className="large-textarea mini-textarea" maxLength={2000} value={question.notes} onChange={e=>patchQuestion({notes:e.target.value})}/></Field></details>
 {error&&<p className="error-message" role="alert">{error}</p>}
 <div className="evidence-suggestions"><h3>Potential evidence from your experience</h3><p className="fine-print">Suggestions use recorded skills and shared topics. Inspect each example; relevance is your decision.</p>
 {suggestions.length?suggestions.slice(0,5).map(({evidence:e,reasons})=><details className="evidence-suggestion" key={evidenceKey(e)}><summary>{e.experienceName} — {e.skill}</summary><p>{reasons.join("; ")}</p><dl><dt>Context</dt><dd>{e.whatHappened||"Not recorded"}</dd><dt>Your recorded action</dt><dd>{e.action}</dd><dt>Learning</dt><dd>{e.learning||"Not recorded"}</dd></dl><p className="fine-print">{e.date||"Date not recorded"} · {starComplete(e)?"Complete STAR recorded":"STAR details may be missing"}</p><div className="detail-actions"><button className="button secondary" onClick={()=>copy(e)}>Copy to draft</button><button className="button secondary" onClick={()=>copy(e,true)}>Build STAR response</button><button className="inline-link" onClick={()=>{setActiveExperience(e.experienceId);navigate("reflect");}}>Inspect source experience</button></div></details>):<p className="card-intro">No recorded examples match this question yet. Browse your evidence or capture one specific action in Experiences.</p>}
 <button className="inline-link" onClick={()=>navigate("evidence")}>Browse all my evidence</button></div>
 {question.evidenceIds.length>0&&<details className="workspace-section"><summary>Evidence used in this draft</summary>{question.evidenceIds.map(id=>{const e=bank.find(v=>evidenceKey(v)===id);return <p key={id}>{e?e.experienceName+" — "+e.skill:"Source evidence was removed. Review any copied text before using this answer."}</p>;})}<p className="fine-print">Copied text is a snapshot. Editing the source does not silently change your answer.</p></details>}
 <div className="detail-actions"><button className="button secondary" onClick={()=>download("sixthstep-answer.txt",question.question+"\n\n"+question.draft+"\n\nNotes: "+question.notes+"\nEvidence references: "+question.evidenceIds.join(", "))}>Export answer</button><button className="button text-button danger" onClick={()=>{if(window.confirm("Delete this question and its draft?")){update({questions:record.questions.filter(q=>q.id!==question.id)});setSelected("");}}}>Remove question</button></div></div>}</>}
 </details></section>;
}
