"use client";
import { recordDeadline, dateLabel, evidenceBank, type TrackedRecord } from "@/lib/domain";
import { applicationPreparation } from "@/lib/application-preparation";
import { applicationPlan } from "@/lib/deadline-plan";
import { lifecycleLabel } from "@/lib/lifecycle";
import { useWorkspace } from "./workspace-context";
export function ApplicationOverview({record,onDeadline,onTask}:{record:TrackedRecord;onDeadline:()=>void;onTask:()=>void}){
 const {data,updateRecord}=useWorkspace(),preparation=applicationPreparation(record,evidenceBank(data.experiences)),plan=applicationPlan(record);
 const update=(patch:Partial<TrackedRecord>)=>updateRecord(record.opportunity.id,patch);
 return (<div className="application-overview"><p className="preparation-status" role="status">{preparation.label}</p>{record.eventDate&&<p><strong>Interview / event:</strong> {dateLabel(record.eventDate)} · Student-entered date</p>}<p><strong>Stage:</strong> {lifecycleLabel(record)} · <strong>Due:</strong> {recordDeadline(record)?dateLabel(recordDeadline(record)):record.opportunity.deadline} · {record.deadlineOverride||record.opportunity.source==="manual"?"Student-entered date":"Provider source — check current details"}</p><p><strong>Needs doing:</strong> {record.nextAction||record.requirements.find(r=>!r.done)?.label||record.questions.find(q=>q.status==="Draft")?.question||"Check the provider requirements and choose your next action"}</p><p><strong>Outstanding:</strong> {record.requirements.filter(r=>!r.done).length} confirmed requirements · {record.questions.filter(q=>q.status==="Draft").length} draft answers</p>
 <section className="application-plan" aria-label="Your plan"><h3>Your plan</h3><p><strong>{plan.basis}:</strong> {plan.target?dateLabel(plan.target):"None recorded"}{plan.daysLeft!==null&&<span>{" · "}{plan.daysLeft<0?Math.abs(plan.daysLeft)+" day"+(Math.abs(plan.daysLeft)===1?"":"s")+" ago":plan.daysLeft===0?"today":plan.daysLeft+" day"+(plan.daysLeft===1?"":"s")+" left"}</span>}</p><p>{plan.note}</p>
 {plan.steps.length>0&&<details className="workspace-section"><summary>Working back from your date ({plan.steps.length} item{plan.steps.length===1?"":"s"})</summary><ol className="plan-steps">{plan.steps.map(step=><li key={step.label}><span>{step.date?dateLabel(step.date):"No date yet"}</span> {step.label}</li>)}</ol><p className="fine-print">These are your own working dates, counted back from the date above. The provider's real deadline decides whether you can apply.</p></details>}</section>
 <div className="detail-actions"><button className="button secondary" onClick={onDeadline}>Add / change deadline</button><button className="button secondary" onClick={onTask}>Add a task or reminder</button></div><ul className="task-list">{record.requirements.filter(r=>!r.done).slice(0,3).map(r=><li key={r.id}><label><input type="checkbox" checked={r.done} onChange={()=>update({requirements:record.requirements.map(t=>t.id===r.id?{...t,done:true}:t)})}/>Complete: {r.label}</label></li>)}</ul></div>);
}