"use client";
import { useState } from "react";
import { reminderKinds } from "@/lib/workspace-events";
import { dateLabel, daysUntil, type TrackedRecord } from "@/lib/domain";
import { useWorkspace } from "./workspace-context";
import { Field } from "./shared";
export function ApplicationTasks({record,open,onOpenChange}:{record:TrackedRecord;open:boolean;onOpenChange:(open:boolean)=>void}){
 const {updateRecord}=useWorkspace(),[checklistText,setChecklistText]=useState(""),[reminderText,setReminderText]=useState(""),[reminderDate,setReminderDate]=useState(""),[reminderKind,setReminderKind]=useState<typeof reminderKinds[number]>("Personal");
 const update=(patch:Partial<TrackedRecord>)=>updateRecord(record.opportunity.id,patch);
 return (<details className="workspace-section" open={open} onToggle={e=>onOpenChange(e.currentTarget.open)}><summary>Personal checklist & reminders</summary><div className="form-grid"><section><h3>Application checklist</h3><p className="fine-print">Add only documents or tasks your provider requires.</p><ul className="task-list">{record.checklist.map(c=><li key={c.id}><label><input type="checkbox" checked={c.done} onChange={()=>update({checklist:record.checklist.map(v=>v.id===c.id?{...v,done:!v.done}:v)})}/><span>{c.label}</span></label><button className="icon-button" aria-label={"Remove checklist item "+c.label} onClick={()=>update({checklist:record.checklist.filter(v=>v.id!==c.id)})}><XIcon/></button></li>)}</ul><form className="inline-form" onSubmit={e=>{e.preventDefault();if(checklistText.trim()&&record.checklist.length<40){update({checklist:[...record.checklist,{id:crypto.randomUUID(),label:checklistText.trim(),done:false}]});setChecklistText("");}}}><input aria-label="New checklist item" className="text-input" maxLength={250} value={checklistText} onChange={e=>setChecklistText(e.target.value)} placeholder="e.g. Teacher reference"/><button className="button secondary" disabled={!checklistText.trim()||record.checklist.length>=40}>Add</button></form></section>
 <section><h3>My reminders</h3><p className="fine-print">Shown in your dashboard. No emails or background notifications.</p><ul className="task-list">{record.reminders.map(r=><li key={r.id}><label><input type="checkbox" checked={r.done} onChange={()=>update({reminders:record.reminders.map(v=>v.id===r.id?{...v,done:!v.done}:v)})}/><span>{r.label}<small>{r.kind} · {dateLabel(r.date)}{(daysUntil(r.date)??0)<0?" · Overdue":""}</small></span></label><button className="icon-button" aria-label={"Remove reminder "+r.label} onClick={()=>update({reminders:record.reminders.filter(v=>v.id!==r.id)})}><XIcon/></button></li>)}</ul><form onSubmit={e=>{e.preventDefault();if(reminderText.trim()&&reminderDate&&record.reminders.length<30){update({reminders:[...record.reminders,{id:crypto.randomUUID(),label:reminderText.trim(),date:reminderDate,done:false,kind:reminderKind}]});setReminderText("");setReminderDate("");}}}><Field label="Reminder type"><select className="text-input" value={reminderKind} onChange={e=>setReminderKind(e.target.value as typeof reminderKinds[number])}>{reminderKinds.map(k=><option key={k}>{k}</option>)}</select></Field><Field label="Reminder text"><input className="text-input" maxLength={250} value={reminderText} onChange={e=>setReminderText(e.target.value)} placeholder="e.g. Prepare questions"/></Field><div className="inline-form"><input aria-label="Reminder date" className="text-input" type="date" required value={reminderDate} onChange={e=>setReminderDate(e.target.value)}/><button className="button secondary" disabled={!reminderText.trim()||!reminderDate||record.reminders.length>=30}>Add reminder</button></div></form></section></div></details>);
}
function XIcon(){return <span aria-hidden="true">×</span>;}
