"use client";
import { useState } from "react";
import { ArrowRight, Plus, Leaf, CalendarDays, Bookmark, CheckCircle2, Link as LinkIcon } from "lucide-react";
import { catalogue } from "@/lib/catalogue";
import { nextSteps, recordDeadline, dateLabel, daysUntil, evidenceBank, type RichOpportunity } from "@/lib/domain";
import { recommendations } from "@/lib/recommendations";
import { useWorkspace } from "./workspace-context";
import { Heading, Empty } from "./shared";
import { OpportunityCard, OpportunityDialog } from "./opportunity";
export function Dashboard(){
 const {data,navigate,setActiveRecord,startImport,startExperience,setActiveExperience}=useWorkspace(),[selected,setSelected]=useState<RichOpportunity|null>(null);
 const steps=nextSteps(data.records,data.experiences);
 const upcoming=data.records.filter(r=>["Saved","Researching","Preparing application"].includes(r.status)&&recordDeadline(r)&&(daysUntil(recordDeadline(r))??-1)>=0).sort((a,b)=>recordDeadline(a).localeCompare(recordDeadline(b))).slice(0,4);
 const waiting=data.records.filter(r=>["Applied","Interview / next stage"].includes(r.status));
 const completed=data.records.filter(r=>r.status==="Completed");
 const evidence=evidenceBank(data.experiences);
 const recommended=recommendations(catalogue,data.profile,data.records.map(r=>r.opportunity.id)).slice(0,3);
 function open(id:string){setActiveRecord(id);navigate("saved");}
 return <><section className="dashboard-welcome"><span className="eyebrow">YOUR NEXT CHAPTER</span><h1>A little progress.<br/><em>A clearer future.</em></h1><p>Discover something worth trying. Make a plan. Keep the learning.</p><div className="dashboard-quick-actions"><button className="button primary" onClick={()=>navigate("finder")}>Find opportunities <ArrowRight size={16}/></button><button className="button secondary" onClick={()=>startImport()}><LinkIcon size={15}/>Paste an opportunity</button></div><span className="welcome-sprig" aria-hidden="true"><Leaf size={76} strokeWidth={1}/></span></section>
 {!data.profile.configured&&<section className="onboarding-card"><div><span className="eyebrow muted">START WITH WHAT MATTERS TO YOU</span><h2>Three small steps. Lots of possibilities.</h2><p>No long questionnaire. Your workspace grows as you use it.</p></div><div className="onboarding-actions"><button onClick={()=>navigate("settings")}><span>01</span><strong>Set my interests</strong><small>Subjects and careers to explore</small><ArrowRight size={16}/></button><button onClick={()=>navigate("finder")}><span>02</span><strong>Find opportunities</strong><small>Explore the source-checked collection</small><ArrowRight size={16}/></button><button onClick={()=>startImport()}><span>03</span><strong>Paste an opportunity I've found</strong><small>Review it, save it, plan your next step</small><ArrowRight size={16}/></button></div></section>}
 <div className="dashboard-grid"><section className="workspace-card"><div className="panel-heading"><h2>Your next steps</h2><button className="inline-link" onClick={()=>navigate("saved")}>My workspace <ArrowRight size={13}/></button></div>
 {steps.length?<ul className="action-list">{steps.slice(0,7).map(step=><li key={step.id}><button onClick={()=>{const r=data.records.find(r=>r.opportunity.id===step.recordId);if(step.kind==="reflection"&&r)startExperience(r);else open(step.recordId);}}><span className={"action-icon "+(step.overdue?"overdue":"")}>{step.kind==="reflection"?<Leaf size={17}/>:step.kind==="deadline"?<CalendarDays size={17}/>:<CheckCircle2 size={17}/>}</span><span><strong>{step.title}</strong><small>{step.date?dateLabel(step.date)+(step.overdue?" · Overdue":""):"Choose a date in your workspace"}{step.priority==="High"?" · High priority":""}</small></span><ArrowRight size={15}/></button></li>)}</ul>:<Empty title="A next step starts with a possibility." action={()=>navigate("finder")} label="Find something to try">Save an opportunity and add a small action, like checking its requirements or asking for a reference.</Empty>}
 </section><section className="workspace-card"><div className="panel-heading"><h2>Upcoming deadlines</h2><CalendarDays size={19}/></div>{upcoming.length?<ul className="action-list">{upcoming.map(r=><li key={r.opportunity.id}><button onClick={()=>open(r.opportunity.id)}><span><strong>{r.opportunity.title}</strong><small>{dateLabel(recordDeadline(r))} · {daysUntil(recordDeadline(r))===0?"Today":daysUntil(recordDeadline(r))+" days remaining"}</small></span><ArrowRight size={15}/></button></li>)}</ul>:<p className="card-intro">No confirmed upcoming deadlines. Add or correct a date in an opportunity workspace. Rolling and unknown dates never get a countdown.</p>}{waiting.length>0&&<><h3 className="section-subtitle">Awaiting a response</h3>{waiting.slice(0,3).map(r=><button className="compact-record" key={r.opportunity.id} onClick={()=>open(r.opportunity.id)}><strong>{r.opportunity.title}</strong><small>{r.status}{r.appliedAt?" · Applied "+dateLabel(r.appliedAt):""}</small><ArrowRight size={13}/></button>)}</>}
 </section></div>
 {recommended.length>0&&<section className="discovery-section"><div className="section-header"><div><h2>Recommended for you</h2><p>Connections to your profile, with the full criteria still to check.</p></div><button className="inline-link" onClick={()=>navigate("finder")}>Explore more <ArrowRight size={13}/></button></div><div className="opportunity-grid">{recommended.map(({item})=><OpportunityCard key={item.id} item={item} onOpen={()=>setSelected(item)}/>)}</div></section>}
 <div className="dashboard-grid"><section className="workspace-card"><div className="panel-heading"><h2>Saved recently</h2><Bookmark size={18}/></div>{data.records.length?data.records.slice().sort((a,b)=>b.savedAt.localeCompare(a.savedAt)).slice(0,4).map(r=><button className="compact-record" key={r.opportunity.id} onClick={()=>open(r.opportunity.id)}><strong>{r.opportunity.title}</strong><small>{r.status} · {r.opportunity.provider}</small><ArrowRight size={14}/></button>):<p className="card-intro">Your saved opportunities will be here when you come back.</p>}</section>
 <section className="workspace-card"><div className="panel-heading"><h2>Turn experience into evidence</h2><Leaf size={19}/></div>{completed.filter(r=>!data.experiences.some(e=>e.opportunityId===r.opportunity.id&&e.whatDid.trim())).slice(0,3).map(r=><button className="compact-record" key={r.opportunity.id} onClick={()=>startExperience(r)}><strong>{r.opportunity.title}</strong><small>Completed · record what you did and learned</small><ArrowRight size={13}/></button>)}<p className="card-intro">{evidence.length?evidence.length+" examples grounded in your own experience, ready to revisit.":"A specific example is more useful than a list of skills. Start with something you actually did."}</p><div className="detail-actions"><button className="button secondary" onClick={()=>navigate("reflect")}>Open my journal <ArrowRight size={14}/></button><button className="inline-link" onClick={()=>navigate("evidence")}>Evidence bank <ArrowRight size={13}/></button></div></section></div>
 <OpportunityDialog item={selected} onClose={()=>setSelected(null)}/></>;
}
