"use client";
import { evidenceKey, starComplete, suggestEvidence } from "@/lib/intelligence";
import type { EvidenceItem } from "@/lib/application-preparation";
import type { TrackedRecord, ApplicationQuestion } from "@/lib/domain";
import { useWorkspace } from "./workspace-context";
export function EvidenceSuggestions({record,question,bank,onCopy}:{record:TrackedRecord;question:ApplicationQuestion;bank:EvidenceItem[];onCopy:(e:EvidenceItem,star?:boolean)=>void}){
 const {navigate,setActiveExperience}=useWorkspace();
 const suggestions=suggestEvidence(question.question,bank,{careerAreas:record.opportunity.careerAreas.length?record.opportunity.careerAreas:[record.opportunity.sector],experienceTypes:[record.opportunity.category]});
 return <details className="evidence-suggestions" open={!question.draft.trim()}><summary>Evidence for this question ({suggestions.length})</summary><p className="fine-print">Matches use your recorded skills, topics and career areas. Inspect the original example before reusing it.</p>{suggestions.length?suggestions.slice(0,5).map(({evidence:e,reasons})=><details className="evidence-suggestion" key={evidenceKey(e)}><summary>{e.experienceName} — {e.skill}</summary><p>{reasons.join("; ")}</p><dl><dt>Context</dt><dd>{e.whatHappened||"Not recorded"}</dd><dt>Your recorded action</dt><dd>{e.action}</dd><dt>Result</dt><dd>{e.star?.result||"Not recorded — add your own result"}</dd><dt>Learning</dt><dd>{e.learning||"Not recorded"}</dd></dl><p className="fine-print">{e.date||"Date not recorded"} · {starComplete(e)?"Complete STAR recorded":"STAR details may be missing"}</p><div className="detail-actions"><button className="button secondary" onClick={()=>onCopy(e)}>Copy to draft</button><button className="button secondary" onClick={()=>onCopy(e,true)}>Build STAR response</button><button className="inline-link" onClick={()=>{setActiveExperience(e.experienceId);navigate("reflect");}}>Inspect source experience</button></div></details>):<p className="card-intro">No recorded examples connect yet. Capture one specific action in Experiences.</p>}<button className="inline-link" onClick={()=>navigate("evidence")}>Browse all my evidence</button></details>;
}
