"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Download, Search, Leaf } from "lucide-react";
import { evidenceBank, dateLabel } from "@/lib/domain";
import { useWorkspace } from "./workspace-context";
import { ReuseEvidence } from "./reuse-evidence";
import { evidenceStrength, starComplete, evidenceKey } from "@/lib/intelligence";
import { Heading, Empty, Field, download, csv } from "./shared";
export function EvidenceBank(){
 const {data,navigate,setActiveExperience,activeEvidence,setActiveEvidence}=useWorkspace(),[filter,setFilter]=useState("All skills"),[query,setQuery]=useState(""),[experienceFilter,setExperienceFilter]=useState("All experiences"),[sector,setSector]=useState("All sectors"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[star,setStar]=useState("Any STAR"),[strength,setStrength]=useState("Any detail"),[sort,setSort]=useState("Recent"),[reuse,setReuse]=useState<{item:ReturnType<typeof evidenceBank>[number];purpose:"Application"|"Interview"}|null>(null);
 const all=evidenceBank(data.experiences),skills=[...new Set(all.map(e=>e.skill))].sort();
 const items=all.filter(e=>!activeEvidence||evidenceKey(e)===activeEvidence).filter(e=>(experienceFilter==="All experiences"||e.experienceId===experienceFilter)&&(sector==="All sectors"||e.sectors.includes(sector))&&(!from||!!e.date&&e.date>=from)&&(!to||!!e.date&&e.date<=to)&&(star==="Any STAR"||star==="Complete STAR"&&starComplete(e)||star==="Incomplete STAR"&&!starComplete(e))&&(strength==="Any detail"||evidenceStrength(e)===strength)&&(filter==="All skills"||e.skill===filter)&&(!query||[e.skill,e.whatHappened,e.action,e.learning,e.experienceName,e.star?.result||"",e.quote].join(" ").toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==="Most detail"?Number(starComplete(b))-Number(starComplete(a))||Number(!!b.whatHappened&&!!b.learning)-Number(!!a.whatHappened&&!!a.learning):(b.date||"").localeCompare(a.date||""));
 const asText=(entries:typeof all)=>entries.map(e=>[e.skill,"Experience: "+e.experienceName+" · "+e.organisation,"Date: "+e.date,"What happened: "+e.whatHappened,"My action: "+e.action,"What I learned: "+e.learning,e.quote?"Original evidence quote: "+e.quote:"",e.star?"STAR\n"+Object.entries(e.star).map(([k,v])=>k+": "+v).join("\n"):""].filter(Boolean).join("\n")).join("\n\n");
 useEffect(()=>{if(activeEvidence)requestAnimationFrame(()=>document.getElementById("evidence-"+encodeURIComponent(activeEvidence))?.focus());},[activeEvidence]);
 return <><Heading eyebrow="YOUR EXPERIENCE, READY TO REUSE" title="Your evidence bank." description="Specific examples from your own experience for applications, CVs and interviews. Every item links back to its source." action={<button className="button secondary" onClick={()=>navigate("reflect")}><Leaf size={16}/>Add evidence in my journal</button>}/>
 {activeEvidence&&<button className="button secondary" onClick={()=>setActiveEvidence("")}>Show all my evidence</button>}<div className="feature-toolbar"><label className="sr-only" htmlFor="evidence-filter">Filter evidence by skill</label><select id="evidence-filter" className="text-input compact-select" value={filter} onChange={e=>setFilter(e.target.value)}><option>All skills</option>{skills.map(s=><option key={s}>{s}</option>)}</select><div className="evidence-search"><Search size={15}/><input aria-label="Search evidence" className="text-input" maxLength={150} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search examples…"/></div><button className="button secondary" disabled={!items.length} onClick={()=>download("sixthstep-evidence-bank.txt",asText(items))}><Download size={15}/>Export examples</button><button className="button text-button" disabled={!all.length} onClick={()=>download("sixthstep-evidence-bank.csv",csv([["Skill","Experience","Organisation","Date","What happened","My action","What I learned","Source quote"],...all.map(e=>[e.skill,e.experienceName,e.organisation,e.date,e.whatHappened,e.action,e.learning,e.quote])]),"text/csv")}>Export CSV</button></div>
 <details className="workspace-section"><summary>Filter by experience, date, sector and detail</summary><div className="form-grid"><Field label="Evidence experience"><select className="text-input" value={experienceFilter} onChange={e=>setExperienceFilter(e.target.value)}><option>All experiences</option>{data.experiences.filter(e=>e.skills.length).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="Evidence sector"><select className="text-input" value={sector} onChange={e=>setSector(e.target.value)}><option>All sectors</option>{[...new Set(all.flatMap(e=>e.sectors))].sort().map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Evidence from date"><input className="text-input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Evidence to date"><input className="text-input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="STAR completeness filter"><select className="text-input" value={star} onChange={e=>setStar(e.target.value)}><option>Any STAR</option><option>Complete STAR</option><option>Incomplete STAR</option></select></Field><Field label="Evidence detail"><select className="text-input" value={strength} onChange={e=>setStrength(e.target.value)}>{["Any detail","Complete STAR","Context, action & learning","Personal action recorded"].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Evidence sort"><select className="text-input" value={sort} onChange={e=>setSort(e.target.value)}><option>Recent</option><option>Most detail</option></select></Field></div><p className="fine-print">Detail indicates fields recorded, not a judgement about your achievement. Undated examples are excluded by date filters.</p><button className="inline-link" onClick={()=>{setExperienceFilter("All experiences");setSector("All sectors");setFrom("");setTo("");setStrength("Any detail");setStar("Any STAR");setFilter("All skills");setQuery("");}}>Clear evidence filters</button></details>{all.length>0&&<p className="fine-print">{all.length} evidence examples across {skills.length} skills. A skill with no personal action stays out of this bank.</p>}
 {!all.length?<Empty title="Start with one real example." action={()=>navigate("reflect")} label="Open my journal">Think of a time you explained something, solved a problem or helped a group. Record what happened, what you did and what you learned.</Empty>:!items.length?<Empty title="No examples with these filters." action={()=>{setExperienceFilter("All experiences");setSector("All sectors");setFrom("");setTo("");setStrength("Any detail");setStar("Any STAR");setFilter("All skills");setQuery("");}} label="Clear evidence filters">Choose another skill or search term.</Empty>:<div className="journal-grid evidence-grid">{items.map(item=><article className="workspace-card evidence-card" id={"evidence-"+encodeURIComponent(evidenceKey(item))} tabIndex={-1} key={item.experienceId+"-"+item.id}><span className="skill-pill">{item.skill}</span><h2>{item.experienceName||"Untitled experience"}</h2><p className="fine-print">{evidenceStrength(item)} · {item.sectors.join(", ")||"Sector not recorded"}</p><p className="provider-name">{item.organisation} {item.date?"· "+dateLabel(item.date):""}</p><dl><dt>What happened</dt><dd>{item.whatHappened||"Not added"}</dd><dt>What I did</dt><dd>{item.action}</dd><dt>Result</dt><dd>{item.star?.result.trim()||"Not recorded — add your own result in the source experience"}</dd><dt>STAR completeness</dt><dd>{item.star?Object.values(item.star).filter(v=>v.trim()).length:0} / 4 fields recorded</dd><dt>What I learned</dt><dd>{item.learning||"Not added"}</dd></dl>{item.quote&&<details><summary>Original supporting quote</summary><blockquote className="evidence-quote">“{item.quote}”</blockquote></details>}{item.star&&<details><summary>STAR example</summary><dl>{Object.entries(item.star).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value||"Not added"}</dd></div>)}</dl></details>}<div className="detail-actions"><button className="button primary" onClick={()=>setReuse({item,purpose:"Application"})}>Use for application</button><button className="inline-link" onClick={()=>{setActiveExperience(item.experienceId);navigate("reflect");}}>View / edit source experience <ArrowRight size={14}/></button><details className="evidence-tools"><summary>More ways to use this example</summary><button className="button secondary" onClick={()=>setReuse({item,purpose:"Interview"})}>Use for interview preparation</button><button className="inline-link" onClick={()=>setActiveEvidence(evidenceKey(item))}>Link to this evidence</button><button className="button text-button" onClick={()=>download("sixthstep-"+item.skill.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-example.txt",asText([item]))}>Export example</button></details></div></article>)}</div>}
 {reuse&&<ReuseEvidence evidence={reuse.item} purpose={reuse.purpose} onClose={()=>setReuse(null)}/>}
 </>;
}
