"use client";
import { useState } from "react";
import { ArrowRight, Download, Search, Leaf } from "lucide-react";
import { evidenceBank, dateLabel } from "@/lib/domain";
import { useWorkspace } from "./workspace-context";
import { Heading, Empty, download, csv } from "./shared";
export function EvidenceBank(){
 const {data,navigate,setActiveExperience}=useWorkspace(),[filter,setFilter]=useState("All skills"),[query,setQuery]=useState("");
 const all=evidenceBank(data.experiences),skills=[...new Set(all.map(e=>e.skill))].sort();
 const items=all.filter(e=>(filter==="All skills"||e.skill===filter)&&(!query||[e.skill,e.action,e.learning,e.experienceName].join(" ").toLowerCase().includes(query.toLowerCase())));
 const asText=(entries:typeof all)=>entries.map(e=>[e.skill,"Experience: "+e.experienceName+" · "+e.organisation,"Date: "+e.date,"What happened: "+e.whatHappened,"My action: "+e.action,"What I learned: "+e.learning,e.quote?"Original evidence quote: "+e.quote:"",e.star?"STAR\n"+Object.entries(e.star).map(([k,v])=>k+": "+v).join("\n"):""].filter(Boolean).join("\n")).join("\n\n");
 return <><Heading eyebrow="YOUR EXPERIENCE, READY TO REUSE" title="Your evidence bank." description="Specific examples from your own experience for applications, CVs and interviews. Every item links back to its source." action={<button className="button secondary" onClick={()=>navigate("reflect")}><Leaf size={16}/>Add evidence in my journal</button>}/>
 <div className="feature-toolbar"><label className="sr-only" htmlFor="evidence-filter">Filter evidence by skill</label><select id="evidence-filter" className="text-input compact-select" value={filter} onChange={e=>setFilter(e.target.value)}><option>All skills</option>{skills.map(s=><option key={s}>{s}</option>)}</select><div className="evidence-search"><Search size={15}/><input aria-label="Search evidence" className="text-input" maxLength={150} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search examples…"/></div><button className="button secondary" disabled={!items.length} onClick={()=>download("sixthstep-evidence-bank.txt",asText(items))}><Download size={15}/>Export examples</button><button className="button text-button" disabled={!all.length} onClick={()=>download("sixthstep-evidence-bank.csv",csv([["Skill","Experience","Organisation","Date","What happened","My action","What I learned","Source quote"],...all.map(e=>[e.skill,e.experienceName,e.organisation,e.date,e.whatHappened,e.action,e.learning,e.quote])]),"text/csv")}>Export CSV</button></div>
 {all.length>0&&<p className="fine-print">{all.length} evidence examples across {skills.length} skills. A skill with no personal action stays out of this bank.</p>}
 {!all.length?<Empty title="Start with one real example." action={()=>navigate("reflect")} label="Open my journal">Think of a time you explained something, solved a problem or helped a group. Record what happened, what you did and what you learned.</Empty>:!items.length?<Empty title="No examples with these filters.">Choose another skill or search term.</Empty>:<div className="journal-grid evidence-grid">{items.map(item=><article className="workspace-card evidence-card" key={item.experienceId+"-"+item.id}><span className="skill-pill">{item.skill}</span><h2>{item.experienceName||"Untitled experience"}</h2><p className="provider-name">{item.organisation} {item.date?"· "+dateLabel(item.date):""}</p><dl><dt>What happened</dt><dd>{item.whatHappened||"Not added"}</dd><dt>What I did</dt><dd>{item.action}</dd><dt>What I learned</dt><dd>{item.learning||"Not added"}</dd></dl>{item.quote&&<details><summary>Original supporting quote</summary><blockquote className="evidence-quote">“{item.quote}”</blockquote></details>}{item.star&&<details><summary>STAR example</summary><dl>{Object.entries(item.star).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value||"Not added"}</dd></div>)}</dl></details>}<div className="detail-actions"><button className="button secondary" onClick={()=>{setActiveExperience(item.experienceId);navigate("reflect");}}>View / edit source experience <ArrowRight size={14}/></button><button className="button text-button" onClick={()=>download("sixthstep-"+item.skill.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-example.txt",asText([item]))}>Export example</button></div></article>)}</div>}
 </>;
}
