"use client";
import { Pathways } from "./pathways";
import { explorationMap } from "@/lib/careers";
import { useWorkspace } from "./workspace-context";
import { Empty, Notice } from "./shared";
export function ExplorationMap(){
 const {data,setActiveExperience,navigate,updateProfile}=useWorkspace(),groups=explorationMap(data.experiences);
 function open(id:string){setActiveExperience(id);navigate("reflect");}
 return <section aria-label="Exploration Map"><h2>Your Exploration Map</h2><p className="card-intro">Notice what you've tried and what you wrote about it. Areas are grouped by your chosen career labels or the experience title; one experience can relate to several areas.</p><Notice>These are prompts for further exploration. SixthStep does not choose a career for you. Your own notes, inferred repetitions and suggested adjacent areas are labelled separately.</Notice>
 {!groups.length?<Empty title="See your interests take shape." action={()=>navigate("reflect")} label="Record an experience">Record an experience, choose the career area it explored and note what you enjoyed or disliked. Those reflections will appear here.</Empty>:<div className="exploration-grid">{groups.map(g=><article className="workspace-card exploration-card" key={g.area}><span className="eyebrow muted">AREA EXPLORED</span><h2>{g.area}</h2><p className="fine-print">{g.entries.length} linked experience{g.entries.length===1?"":"s"}</p>
 {(["enjoyed","disliked","impact","next"] as const).map(field=><section key={field}><h3>{({enjoyed:"You wrote: enjoyed",disliked:"You wrote: less interested in",impact:"You wrote: career impact",next:"Your own next steps"})[field]}</h3>{g[field].length?g[field].map(v=><blockquote className="map-quote" key={v.id}>{v.text}<button className="inline-link" onClick={()=>open(v.id)}>{v.name} · {v.date||"Undated"}</button></blockquote>):<p className="fine-print">No notes recorded for this yet.</p>}</section>)}
 <details className="workspace-section"><summary>Inferred patterns · repeated words</summary>{g.repeated.length?g.repeated.map((r,i)=><p key={i}>“{r.text}” appears in your {r.field} notes for {r.sources.length} experiences. This is a textual repetition, not a career judgement.</p>):<p className="fine-print">No repeated phrasing across separate experiences. We won't infer a preference from a programme description or an AI draft.</p>}</details>
 <h3>Suggested adjacent areas to explore</h3><p className="fine-print">From SixthStep's explicit career relationships, not a prediction about you.</p><div className="suggestion-chips">{g.suggestions.map(area=><button key={area} className="quick-filter" onClick={()=>{updateProfile({...data.profile,careerInterests:[data.profile.careerInterests,area].filter(Boolean).join(", ").slice(0,400),configured:true,direction:"Exploring"});navigate("finder");}}>Explore {area}</button>)}</div><details className="workspace-section"><summary>Linked experiences and recorded interest</summary>{g.entries.map(e=><button key={e.id} className="compact-record" onClick={()=>open(e.id)}><strong>{e.name}</strong><small>You recorded: {e.interestChange.toLowerCase()} interest</small></button>)}</details></article>)}</div>}<Pathways/></section>;
}
