"use client";
import { useEffect, useRef, useState } from "react";
import { Plus, Sparkles, LoaderCircle, Trash2, Leaf, ArrowLeft } from "lucide-react";
import { experienceSchema, skillNames, reflectionInput, todayISO, type Experience, type SkillEvidence, type RichReflection } from "@/lib/domain";
import { DevelopmentTimeline } from "./development-timeline";
import { ExplorationMap } from "./exploration-map";
import { ReflectionGuide } from "./reflection-guide";
import { studentEvidenceText } from "@/lib/grounding";
import { useWorkspace } from "./workspace-context";
import { Heading, Field, Notice, Empty, ExportButton } from "./shared";
function newExperience():Experience{return experienceSchema.parse({id:crypto.randomUUID(),name:"Untitled experience",updatedAt:new Date().toISOString()});}
function experienceText(e:Experience){return [e.name,"Organisation: "+e.organisation,"Date: "+e.date,"Hours: "+e.hours,"Type: "+e.type,reflectionInput(e),"SKILL EVIDENCE",...e.skills.map(s=>s.skill+"\nWhat happened: "+s.whatHappened+"\nMy action: "+s.action+"\nLearning: "+s.learning+(s.quote?"\nSource quote: "+s.quote:"")),e.reflection?"EDITED REFLECTION\n"+e.reflection.summary+"\nCV: "+e.reflection.cvBullet+"\nApplication: "+e.reflection.applicationExample+"\nInterview: "+e.reflection.interviewTalkingPoint:""].join("\n\n");}
export function Journal(){
 const {data,activeExperience,setActiveExperience,updateExperience,removeExperience,connections,toast,navigate}=useWorkspace();
 const experience=data.experiences.find(e=>e.id===activeExperience);
 const [journey,setJourney]=useState(false);
 const [map,setMap]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [skill,setSkill]=useState<string>(skillNames[0]),[happened,setHappened]=useState(""),[action,setAction]=useState(""),[learning,setLearning]=useState("");
 useEffect(()=>{if(activeExperience){setJourney(false);setMap(false);}},[activeExperience]);
 const [pending,setPending]=useState<{id:string;notes:string;value:RichReflection}|null>(null);
 const currentId=useRef(activeExperience);
 useEffect(()=>{currentId.current=activeExperience;setError("");setHappened("");setAction("");setLearning("");},[activeExperience]);
 const update=(patch:Partial<Experience>)=>{if(experience)updateExperience({...experience,...patch,updatedAt:new Date().toISOString()});};
 function add(){setMap(false);const entry=newExperience();updateExperience(entry);setActiveExperience(entry.id);setPending(null);setError("");}
 async function reflect(){
  if(!experience||busy)return;
  setBusy(true);setError("");setPending(null);
  const snapshot=experience.id,notes=studentEvidenceText(experience);
  try{const response=await fetch("/api/experience-reflection",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...experience,reflection:undefined})});const result=await response.json();if(!response.ok)throw new Error(result.error);setPending({id:snapshot,notes,value:result.reflection});}
  catch(e){if(currentId.current===snapshot)setError(e instanceof Error?e.message:"Reflection could not complete.");}finally{setBusy(false);}
 }
 const output=(pending?.id===experience?.id?pending?.value:null)||experience?.reflection;
 const setOutput=(value:RichReflection)=>{if(experience)setPending({id:experience.id,notes:pending?.id===experience.id?pending.notes:studentEvidenceText(experience),value});};
 function addAiEvidence(index:number){
  if(!experience||!output)return;
  const value=output.skills[index];
  const item:SkillEvidence={id:crypto.randomUUID(),skill:value.skill,whatHappened:value.whatHappened,action:value.action,learning:value.learning,quote:value.evidenceQuote};
  if(experience.skills.length>=30)return;
  if(experience.skills.some(s=>s.skill===item.skill&&s.quote===item.quote)){toast("This evidence is already in your bank");return;}
  update({skills:[...experience.skills,item]});toast("Evidence added and linked to this experience");
 }
 return <><Heading eyebrow="TURN EXPERIENCE INTO UNDERSTANDING" title="Your experience journal." description="Record what you actually did, keep useful evidence and notice what you want to explore next." action={<button className="button primary" onClick={add}><Plus size={16}/>New experience</button>}/>
 <div className="explore-nav" role="group" aria-label="Experience workflows"><button className={"button "+(!map&&!journey?"primary":"secondary")} aria-pressed={!map&&!journey} onClick={()=>{setMap(false);setJourney(false);}}>My experiences</button><details className="explore-tools"><summary>Explore your learning</summary><button className={"button "+(map?"primary":"secondary")} aria-pressed={map} onClick={()=>{setActiveExperience("");setMap(true);setJourney(false);}}>Exploration Map</button><button className={"button "+(journey?"primary":"secondary")} aria-pressed={journey} onClick={()=>{setActiveExperience("");setJourney(true);setMap(false);}}>Development timeline</button><button className="button secondary" onClick={()=>navigate("evidence")}>My evidence</button></details></div>
 {journey?<DevelopmentTimeline/>:map?<ExplorationMap/>:!experience?data.experiences.length?<div className="journal-grid">{data.experiences.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(e=><article className="workspace-card journal-card" key={e.id}><span className="workspace-icon"><Leaf size={22}/></span><h2>{e.name||"Untitled experience"}</h2><p className="provider-name">{e.organisation||"Organisation not added"}</p><p className="card-intro">{e.whatDid?e.whatDid.slice(0,160):"Ready for your own notes."}</p><p className="fine-print">{e.date||"Date not added"} · {e.skills.filter(s=>s.action.trim()).length} evidence examples</p><button className="button secondary" onClick={()=>{setActiveExperience(e.id);setPending(null);setError("");}}>Open experience <ArrowLeft size={13} className="rotate-arrow"/></button></article>)}</div>:<Empty title="There's learning in every experience." action={add} label="Record an experience">Start with a programme you completed, an insight event, a competition or an activity outside school. Completed tracked opportunities can also become journal entries.</Empty>:<>
 <button className="button text-button back-link" onClick={()=>{setActiveExperience("");setPending(null);}}> <ArrowLeft size={15}/>All experiences</button>
 <div className="workspace-grid journal-editor"><section className="workspace-card"><h2>What happened?</h2><p className="card-intro">Your notes save automatically in this browser. No AI is needed to keep useful evidence.</p>
 <div className="form-grid"><Field label="Experience name"><input className="text-input" maxLength={180} value={experience.name} onChange={e=>update({name:e.target.value})}/></Field><Field label="Organisation"><input className="text-input" maxLength={180} value={experience.organisation} onChange={e=>update({organisation:e.target.value})}/></Field><Field label="Experience date"><input className="text-input" type="date" value={experience.date} onChange={e=>update({date:e.target.value})}/></Field><Field label="Duration / hours"><input className="text-input" maxLength={80} value={experience.hours} onChange={e=>update({hours:e.target.value})} placeholder="e.g. 6 hours or 2 days"/></Field></div>
 <Field label="Experience type"><select className="text-input" value={experience.type} onChange={e=>update({type:e.target.value})}>{[...new Set([experience.type,"Work experience","Virtual work experience","Job simulation","Employer insight","Summer school","Competition","Volunteering","Part-time work","Lecture / academic event","Personal project","Not stated"])].map(v=><option key={v}>{v}</option>)}</select></Field>
 <Field label="What I did" hint="Describe your actions, not what the programme advertised."><textarea className="large-textarea short-textarea" maxLength={4500} value={experience.whatDid} onChange={e=>update({whatDid:e.target.value})} placeholder="I compared two design options and explained my choice…"/></Field>
 <Field label="What I learned"><textarea className="large-textarea short-textarea" maxLength={2500} value={experience.learned} onChange={e=>update({learned:e.target.value})} placeholder="This helped me understand…"/></Field>
 <Field label="What I enjoyed"><textarea className="large-textarea mini-textarea" maxLength={1500} value={experience.enjoyed} onChange={e=>update({enjoyed:e.target.value})}/></Field><Field label="Recorded change in career interest"><select className="text-input" value={experience.interestChange} onChange={e=>update({interestChange:e.target.value as Experience["interestChange"]})}>{["Unsure","Increased","Decreased","Mixed","Unchanged"].map(v=><option key={v}>{v}</option>)}</select></Field><details className="profile-preferences"><summary>Go a little deeper</summary>{[
 ["challenges","Challenges I faced"],["surprised","What surprised me"],["disliked","What I disliked"],["careerImpact","How it affected my career interests"],["nextStep","My next step"]
 ].map(([key,label])=><Field key={key} label={label}><textarea className="large-textarea mini-textarea" maxLength={key==="nextStep"?1000:1500} value={experience[key as "challenges"]} onChange={e=>update({[key]:e.target.value})}/></Field>)}</details>
 <div className="detail-actions"><button className="button primary" disabled={!experience.whatDid.trim()||!experience.learned.trim()} onClick={()=>{update({reflectionCompletedAt:todayISO()});toast("Reflection saved. Keep a specific example for your evidence bank.");}}>Save core reflection</button>{experience.reflectionCompletedAt&&<span className="fine-print" role="status">Reflection recorded · {experience.reflectionCompletedAt}</span>}</div><ReflectionGuide key={experience.id} experience={experience} update={update}/><details className="evidence-form"><summary>Capture a skill with evidence</summary><form onSubmit={e=>{e.preventDefault();if(!action.trim()||!skill.trim()||experience.skills.length>=30)return;update({skills:[...experience.skills,{id:crypto.randomUUID(),skill,whatHappened:happened,action,learning,quote:""}]});setHappened("");setAction("");setLearning("");toast("Your evidence is now in the evidence bank");}}>
 <Field label="Skill"><select className="text-input" value={skill} onChange={e=>setSkill(e.target.value)}>{skillNames.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="What happened"><textarea className="large-textarea mini-textarea" maxLength={1200} value={happened} onChange={e=>setHappened(e.target.value)}/></Field><Field label="What I personally did"><textarea className="large-textarea mini-textarea" maxLength={1500} required value={action} onChange={e=>setAction(e.target.value)}/></Field><Field label="What I learned from this"><textarea className="large-textarea mini-textarea" maxLength={1200} value={learning} onChange={e=>setLearning(e.target.value)}/></Field><button className="button secondary" disabled={!action.trim()||experience.skills.length>=30}>Add to evidence bank</button></form></details>
 {experience.skills.length>0&&<div className="entry-evidence"><h3>Evidence from this experience</h3>{experience.skills.map(s=><details key={s.id}><summary>{s.skill}</summary><Field label={"What happened — "+s.skill}><textarea className="large-textarea mini-textarea" maxLength={1200} value={s.whatHappened} onChange={e=>update({skills:experience.skills.map(v=>v.id===s.id?{...v,whatHappened:e.target.value}:v)})}/></Field><Field label={"My action — "+s.skill}><textarea className="large-textarea mini-textarea" maxLength={1500} value={s.action} onChange={e=>update({skills:experience.skills.map(v=>v.id===s.id?{...v,action:e.target.value}:v)})}/></Field><Field label={"Learning — "+s.skill}><textarea className="large-textarea mini-textarea" maxLength={1200} value={s.learning} onChange={e=>update({skills:experience.skills.map(v=>v.id===s.id?{...v,learning:e.target.value}:v)})}/></Field><details><summary>Optional STAR structure</summary>{(["situation","task","action","result"] as const).map(key=><Field key={key} label={key[0].toUpperCase()+key.slice(1)+" — "+s.skill}><textarea className="large-textarea mini-textarea" maxLength={key==="action"?1500:1000} value={s.star?.[key]||""} onChange={e=>update({skills:experience.skills.map(v=>v.id===s.id?{...v,star:{situation:"",task:"",action:"",result:"",...v.star,[key]:e.target.value}}:v)})}/></Field>)}</details>{s.quote&&<blockquote className="evidence-quote">Original evidence quote: “{s.quote}”</blockquote>}<button className="button text-button danger" onClick={()=>update({skills:experience.skills.filter(v=>v.id!==s.id)})}>Remove this evidence</button></details>)}</div>}
 <div className="detail-actions"><ExportButton name="sixthstep-experience-notes.txt" text={experienceText(experience)} label="Export my notes"/><button className="button text-button danger" onClick={()=>{if(window.confirm("Delete this experience and its linked evidence? The tracked opportunity will be kept.")){removeExperience(experience.id);setActiveExperience("");setPending(null);}}}><Trash2 size={15}/>Delete experience</button></div></section>
 <details className="workspace-card summary-output" open={!!output}><summary>Optional AI reflection</summary><span className="workspace-icon"><Sparkles size={22}/></span><h2>Find the words for your learning</h2><p className="card-intro">AI can help organise your own evidence into a reflection, CV bullet, STAR example and interview talking point.</p><Notice>AI reflection sends this experience's notes to {connections?.aiProvider||"the configured AI provider"}. Leave out names and private details. Check every statement before reusing it.</Notice>
 <button className="button primary wide" disabled={busy||studentEvidenceText(experience).trim().length<60} onClick={()=>void reflect()}>{busy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {busy?"Reflecting on your evidence…":"Help me reflect"}</button><p className="input-hint">{studentEvidenceText(experience).trim().length<60?"Add at least 60 characters of your own evidence to use AI.":"Only this selected experience is submitted."}</p>{error&&<p className="error-message" role="alert">{error}</p>}
 {pending?.id===experience.id&&pending.notes!==studentEvidenceText(experience)&&<p className="error-message" role="alert">These suggestions use an earlier version of your notes. Review them against your current notes before saving or reusing evidence.</p>}{output&&<div className="reflection-review"><span className="eyebrow muted">REVIEW & MAKE IT YOURS</span>{[
 ["summary","Concise reflection",2200],["cvBullet","CV bullet",700],["applicationExample","Application-ready example",1800],["interviewTalkingPoint","Interview talking point",1200]
 ].map(([key,label,max])=><Field key={key} label={String(label)}><textarea className="large-textarea short-textarea" maxLength={Number(max)} value={output[key as "summary"]} onChange={e=>setOutput({...output,[key]:e.target.value})}/></Field>)}
 <details className="profile-preferences" open><summary>STAR example</summary>{(["situation","task","action","result"] as const).map(key=><Field key={key} label={"STAR "+key}><textarea className="large-textarea mini-textarea" maxLength={key==="action"?1500:1000} value={output.star[key]} onChange={e=>setOutput({...output,star:{...output.star,[key]:e.target.value}})}/></Field>)}</details>
 <h3>Skills linked to your words</h3>{output.skills.map((s,i)=><div className="generated-evidence" key={i}><strong>{s.skill}</strong><blockquote>“{s.evidenceQuote}”</blockquote><p>{s.action}</p><p className="fine-print">{s.learning}</p><details className="profile-preferences"><summary>Edit this skill example</summary>{(["skill","whatHappened","action","learning"] as const).map(key=><Field key={key} label={({"skill":"Suggested skill","whatHappened":"Suggested context","action":"Suggested personal action","learning":"Suggested learning"}[key])+" "+(i+1)}><textarea className="large-textarea mini-textarea" maxLength={key==="skill"?100:key==="action"?1200:1000} value={s[key]} onChange={e=>setOutput({...output,skills:output.skills.map((item,j)=>j===i?{...item,[key]:e.target.value}:item)})}/></Field>)}</details><button className="button secondary" onClick={()=>addAiEvidence(i)} disabled={experience.skills.length>=30}>Use this evidence</button></div>)}
 <Field label="Suggested follow-up actions"><textarea className="large-textarea short-textarea" maxLength={2500} value={output.nextSteps.join("\n")} onChange={e=>setOutput({...output,nextSteps:e.target.value.split("\n").slice(0,5).map(v=>v.slice(0,500))})}/></Field>
 <div className="detail-actions"><button className="button primary" onClick={()=>{update({reflection:output});setPending(null);toast("Edited reflection saved with this experience");}}>Save edited reflection</button><ExportButton name="sixthstep-reflection.txt" label="Export reflection" text={[output.summary,"STAR\n"+Object.entries(output.star).map(([k,v])=>k+": "+v).join("\n"),"CV\n"+output.cvBullet,"Application\n"+output.applicationExample,"Interview\n"+output.interviewTalkingPoint,"Next steps\n"+output.nextSteps.join("\n")].join("\n\n")}/></div></div>}
 </details></div></>}
 </>;
}
