"use client";
import { useEffect, useState } from "react";
import { Sparkles, Search, Download, Upload, ArrowRight } from "lucide-react";
import { sectors } from "@/lib/types";
import { categories, formats, profileSchema, type StudentProfile, type AppData } from "@/lib/domain";
import { backupJSON, restoreWorkspace } from "@/lib/persistence";
import { useWorkspace } from "./workspace-context";
import { Heading, Field, Notice, download } from "./shared";
import { LocalMetrics } from "./local-metrics";
export function Profile(){
 const {data,updateProfile,connections,navigate,toast,replaceData,recovery}=useWorkspace();
 const [draft,setDraft]=useState<StudentProfile>(data.profile),[subjects,setSubjects]=useState(data.profile.subjects.join(", ")),[error,setError]=useState("");
 const [restore,setRestore]=useState<AppData|null>(null);
 useEffect(()=>{setDraft(data.profile);setSubjects(data.profile.subjects.join(", "));},[data.profile]);
 const update=(patch:Partial<StudentProfile>)=>setDraft(current=>({...current,...patch}));
 function save(){const parsed=profileSchema.safeParse({...draft,subjects:subjects.split(/[,;\n]/).map(s=>s.trim()).filter(Boolean),configured:true});if(!parsed.success){setError("Check your age and shorten any long fields.");return;}updateProfile(parsed.data);setError("");toast("Profile saved. Your recommendations now use these preferences.");}
 async function readBackup(file:File|undefined){if(!file)return;try{if(file.size>5000000)throw new Error("This backup is too large.");setRestore(restoreWorkspace(await file.text()));setError("");}catch(e){setError(e instanceof Error?e.message:"This backup could not be read.");}}
 return <><Heading eyebrow="MAKE THIS SPACE YOURS" title="Your interests. Your direction." description="Start with your year, subjects and interests. Add preferences when they become useful."/>
 <div className="workspace-grid"><section className="workspace-card"><h2>A few useful details</h2><p className="card-intro">Kept in this browser. Matching uses your profile locally; it is not sent to AI automatically.</p><form onSubmit={e=>{e.preventDefault();save();}}>
 <div className="form-grid"><Field label="School year"><select className="text-input" value={draft.year} onChange={e=>update({year:e.target.value})}><option>Year 12</option><option>Year 13</option><option>S5</option><option>S6</option><option>Year 13 (Northern Ireland)</option><option>Year 14 (Northern Ireland)</option><option>Other</option><option>Equivalent year group</option><option>Exploring sixth form</option></select></Field><Field label="Age" hint="Optional; check age-at-programme-start rules too."><select className="text-input" value={draft.age} onChange={e=>update({age:e.target.value})}><option value="">Prefer not to add</option>{[15,16,17,18,19,20].map(a=><option key={a} value={a}>{a}</option>)}</select></Field></div>
 <Field label="Subjects you're studying" hint="Separate subjects with commas"><input className="text-input" maxLength={500} value={subjects} onChange={e=>setSubjects(e.target.value)} placeholder="Maths, Physics, English…"/></Field>
 <p className="field-label">Sectors I want to explore</p><div className="interest-grid">{sectors.slice(1).map(sector=><button type="button" className={"interest-button "+(draft.interests.includes(sector)?"selected":"")} key={sector} aria-pressed={draft.interests.includes(sector)} onClick={()=>update({interests:draft.interests.includes(sector)?draft.interests.filter(s=>s!==sector):[...draft.interests,sector]})}>{sector}</button>)}</div>
 <Field label="Career interests" hint="Optional: a role, field or question you're curious about"><input className="text-input" maxLength={400} value={draft.careerInterests} onChange={e=>update({careerInterests:e.target.value})} placeholder="e.g. Aerospace engineering or healthcare"/></Field>
 <Field label="Where am I in my exploration?"><select className="text-input" value={draft.direction} onChange={e=>update({direction:e.target.value as StudentProfile["direction"]})}><option>Exploring</option><option>Targeting a field</option></select></Field><p className="fine-print">Exploring gives adjacent fields more weight. Targeting prioritises direct career connections. Saved interests and experiences where you recorded increased interest can add explained connections.</p>
 <details className="profile-preferences"><summary>More preferences, when you're ready</summary><div className="form-grid"><Field label="Preferred format"><select className="text-input" value={draft.format} onChange={e=>update({format:e.target.value as StudentProfile["format"]})}><option>Any</option>{formats.filter(f=>f!=="Not stated").map(f=><option key={f}>{f}</option>)}</select></Field><Field label="Preferred duration"><select className="text-input" value={draft.duration} onChange={e=>update({duration:e.target.value})}>{["Any","A few hours","1–3 days","4–7 days","1–2 weeks","Several weeks","Longer programme","Self-paced"].map(d=><option key={d}>{d}</option>)}</select></Field><Field label="Approximate location / travel area" hint="Town or region, not your address"><input className="text-input" maxLength={150} value={draft.location} onChange={e=>update({location:e.target.value})} placeholder="e.g. Bristol / South West"/></Field><Field label="Willingness to travel"><select className="text-input" value={draft.travel} onChange={e=>update({travel:e.target.value as StudentProfile["travel"]})}>{["Not sure","Local only","Within my region","Anywhere in the UK","International"].map(t=><option key={t}>{t}</option>)}</select></Field></div>
 <p className="field-label">Preferred opportunity types</p><div className="interest-grid">{categories.filter(c=>!["Not stated","Provider directory"].includes(c)).map(c=><button type="button" className={"interest-button "+(draft.preferredTypes.includes(c)?"selected":"")} aria-pressed={draft.preferredTypes.includes(c)} key={c} onClick={()=>update({preferredTypes:draft.preferredTypes.includes(c)?draft.preferredTypes.filter(v=>v!==c):[...draft.preferredTypes,c]})}>{c}</button>)}</div>
 <Field label="Interests outside school"><input className="text-input" maxLength={500} value={draft.outsideInterests} onChange={e=>update({outsideInterests:e.target.value})} placeholder="Music, volunteering, sport, building things…"/></Field></details>
 {error&&<p className="error-message" role="alert">{error}</p>}<div className="detail-actions"><button className="button primary">Save my profile</button><button type="button" className="button text-button" onClick={()=>navigate("finder")}>Explore opportunities <ArrowRight size={14}/></button></div></form><p className="fine-print">Connections are explained, not scored as percentages. Outside interests and your exploration direction are included where relevant; grades and widening-participation criteria still need checking.</p></section>
 <div className="stacked-panels"><section className="workspace-card"><h2>AI & search connections</h2><p className="card-intro">The finder, tracker, journal and manual evidence bank work without keys.</p><div className="connection-row"><span className="workspace-icon"><Sparkles size={20}/></span><div><strong>{connections?.aiProvider||"AI provider"}</strong><p>Extraction & reflections</p></div><span className={"connection-status "+(connections?.ai?"connected":"")}>{connections===null?"Checking":connections.ai?"Configured":connections.aiSetup==="invalid"?"Check setup":"Needs setup"}</span></div><div className="connection-row"><span className="workspace-icon"><Search size={20}/></span><div><strong>Tavily</strong><p>Web search & link extraction</p></div><span className={"connection-status "+(connections?.search?"connected":"")}>{connections===null?"Checking":connections.search?"Configured":"Needs setup"}</span></div>
 <details className="setup-details"><summary>How to connect an AI provider</summary><p>In Vercel Settings → Environment Variables, add <code>GROQ_API_KEY</code> or your compatible provider's <code>OPENAI_API_KEY</code>, <code>OPENAI_BASE_URL</code> and <code>OPENAI_MODEL</code>. Compatible settings take priority.</p><p>Add <code>TAVILY_API_KEY</code> for web search and reading opportunity URLs, then redeploy.</p><p>Use a public HTTPS API base, such as <code>https://api.openai.com/v1</code>. Optional <code>OPENAI_PROVIDER_NAME</code> sets the public label.</p><p>For providers requiring the older token field, set <code>OPENAI_TOKEN_PARAMETER=max_tokens</code>. To disable response-format JSON mode, set <code>OPENAI_JSON_MODE=false</code>.</p><p>Configured means settings are present. Keys remain on the server; never paste them into student pages. Choose a provider whose terms suit your students; pricing and free allowances vary.</p></details><Notice>AI sends only submitted opportunity text or selected experience notes to the configured provider. Link extraction and web search use Tavily. Avoid private or identifying information.</Notice></section>
 <LocalMetrics/><section className="workspace-card"><h2>Keep a copy of your progress</h2><p className="card-intro">Local data does not sync across devices. A JSON backup keeps profiles, applications, experiences and evidence together.</p><button className="button secondary" onClick={()=>download("sixthstep-workspace-backup.json",backupJSON(data),"application/json")}><Download size={15}/>Export workspace backup</button><label className="backup-upload"><Upload size={15}/>Restore a backup<input type="file" accept=".json,application/json" aria-label="Restore workspace backup" onChange={e=>{void readBackup(e.target.files?.[0]);e.target.value="";}}/></label>
 {restore&&<div className="notice backup-review"><div><p>This backup contains {restore.records.length} opportunities and {restore.experiences.length} experiences. Restoring replaces this browser's current workspace.</p><div className="detail-actions"><button className="button primary" onClick={()=>{replaceData(restore);setRestore(null);}}>Restore this workspace</button><button className="button secondary" onClick={()=>setRestore(null)}>Cancel</button></div></div></div>}
 {error&&<p className="error-message" role="alert">{error}</p>}<button className="button text-button" onClick={()=>{void recovery().then(legacy=>download("sixthstep-original-storage.json",JSON.stringify(legacy,null,2),"application/json")).catch(()=>setError("Original storage is unavailable. Export your current workspace instead."));}}>Export raw stored data</button><p className="fine-print">This is the raw data this browser held before SixthStep last saved, which is what support would ask for if your workspace will not load. It is a diagnostic dump, not a restorable backup: use "Restore a backup" only with a file from "Export workspace backup".</p></section></div></div></>;
}
