"use client";
import { useState } from "react";
import { profileSchema } from "@/lib/domain";
import { useWorkspace } from "./workspace-context";
import { Field } from "./shared";
export function QuickSetup(){
 const {data,updateProfile,navigate}=useWorkspace(),[step,setStep]=useState(0),[profile,setProfile]=useState(data.profile),[subjects,setSubjects]=useState(data.profile.subjects.join(", ")),[interests,setInterests]=useState(data.profile.interests.join(", "));
 const [error,setError]=useState("");
 const patch=(value:Partial<typeof profile>)=>setProfile(p=>({...p,...value}));
 return <section className="workspace-card quick-setup" aria-label="Quick student setup"><span className="eyebrow">START WITH WHAT YOU KNOW</span><h2>A few details. Useful possibilities.</h2><p className="card-intro">Step {step+1} of 3. Add only what helps you discover; you can change or skip optional details.</p><form onSubmit={e=>{e.preventDefault();if(step<2)setStep(step+1);else{const parsed=profileSchema.safeParse({...profile,subjects:subjects.split(",").map(v=>v.trim()).filter(Boolean),interests:interests.split(",").map(v=>v.trim()).filter(Boolean),configured:true});if(!parsed.success){setError("Use up to 30 subjects and interests with names shorter than 120 characters. You can go Back to edit them.");return;}updateProfile(parsed.data);navigate("finder");}}}>
 {step===0?<div className="form-grid"><Field label="Your school year"><select className="text-input" value={profile.year} onChange={e=>patch({year:e.target.value})}><option>Year 12</option><option>Year 13</option><option>S5</option><option>S6</option><option>Year 13 (Northern Ireland)</option><option>Year 14 (Northern Ireland)</option><option>Other</option></select></Field><Field label="Subjects you study" hint="Separate with commas; optional."><input className="text-input" maxLength={600} value={subjects} onChange={e=>setSubjects(e.target.value)} placeholder="Physics, Maths, Computer Science"/></Field></div>:step===1?<div className="form-grid"><Field label="Broad interests" hint="Separate with commas; optional."><input className="text-input" maxLength={600} value={interests} onChange={e=>setInterests(e.target.value)} placeholder="Engineering, healthcare, volunteering"/></Field><Field label="Career areas you are considering" hint="Exploration is enough; optional."><input className="text-input" maxLength={400} value={profile.careerInterests} onChange={e=>patch({careerInterests:e.target.value})} placeholder="Not sure yet, or a few ideas…"/></Field></div>:<div className="form-grid"><Field label="Approximate location" hint="Town or region, no address; optional."><input className="text-input" maxLength={150} value={profile.location} onChange={e=>patch({location:e.target.value})}/></Field><Field label="Preferred opportunity format"><select className="text-input" value={profile.format} onChange={e=>patch({format:e.target.value as typeof profile.format})}><option>Any</option><option>Virtual</option><option>In person</option><option>Hybrid</option></select></Field></div>}
 {error&&<p className="error-message" role="alert">{error}</p>}<div className="detail-actions">{step>0&&<button type="button" className="button secondary" onClick={()=>setStep(step-1)}>Back</button>}<button className="button primary">{step===2?"Show my opportunities":"Continue"}</button><button type="button" className="inline-link" onClick={()=>navigate("settings")}>Set my interests in Profile</button></div></form></section>;
}
