"use client";
import { useState } from "react";
import { careerLinks } from "@/lib/careers";
import { skillNames, todayISO, type Experience } from "@/lib/domain";
import { Field } from "./shared";
import { useWorkspace } from "./workspace-context";
export function ReflectionGuide({experience,update}:{experience:Experience;update:(patch:Partial<Experience>)=>void}){
 const {toast,navigate}=useWorkspace(),[step,setStep]=useState(0),[open,setOpen]=useState(!experience.whatDid.trim()),[skill,setSkill]=useState<string>("Problem solving"),[action,setAction]=useState(""),[context,setContext]=useState("");
 const titles=["What actually happened?","What caught your interest?","What did you learn?","Keep one specific example","What would you explore next?"];
 const field=(key:"whatDid"|"enjoyed"|"disliked"|"surprised"|"challenges"|"learned"|"careerImpact"|"nextStep",label:string,max:number)=><Field label={"Reflection: "+label}><textarea className="large-textarea short-textarea" maxLength={max} value={experience[key]} onChange={e=>update({[key]:e.target.value})}/></Field>;
 return <details className="reflection-guide" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Short guided reflection</summary><p className="eyebrow muted">PROMPT {step+1} OF 5 · SAVES AS YOU WRITE</p><h3>{titles[step]}</h3>
 {step===0&&<>{field("whatDid","what did you personally do?",4500)}<p className="fine-print">Use your own actions. Attending a programme does not prove you performed its advertised tasks.</p></>}
 {step===1&&<>{field("enjoyed","most interesting or enjoyable part",1500)}{field("disliked","what interested you less",1500)}{field("surprised","what surprised you",1500)}</>}
 {step===2&&<>{field("challenges","what was difficult?",1500)}{field("learned","what did you learn?",2500)}</>}
 {step===3&&<><Field label="Reflection: skill demonstrated"><select className="text-input" value={skill} onChange={e=>setSkill(e.target.value)}>{skillNames.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Reflection: situation for this example"><textarea className="large-textarea mini-textarea" maxLength={1200} value={context} onChange={e=>setContext(e.target.value)}/></Field><Field label="Reflection: specific action that proves it"><textarea className="large-textarea mini-textarea" maxLength={1500} value={action} onChange={e=>setAction(e.target.value)}/></Field><button className="button secondary" disabled={!action.trim()||experience.skills.length>=30} onClick={()=>{update({skills:[...experience.skills,{id:crypto.randomUUID(),skill,whatHappened:context,action,learning:experience.learned.slice(0,1200),quote:""}]});setAction("");setContext("");toast("Specific example added to your Evidence Bank");}}>Keep this evidence example</button><p className="fine-print">{experience.skills.length} example(s) already recorded. You can add STAR details in the evidence editor below.</p></>}
 {step===4&&<><Field label="Reflection: career area for grouping"><select className="text-input" value={experience.careerAreas[0]||""} onChange={e=>update({careerAreas:e.target.value?[e.target.value]:[]})}><option value="">Not yet decided</option>{[...new Set([...experience.careerAreas,...careerLinks.map(a=>a.area)])].map(a=><option key={a}>{a}</option>)}</select></Field><Field label="Reflection: change in career interest"><select className="text-input" value={experience.interestChange} onChange={e=>update({interestChange:e.target.value as Experience["interestChange"]})}>{["Unsure","Increased","Decreased","Mixed","Unchanged"].map(a=><option key={a}>{a}</option>)}</select></Field>{field("careerImpact","how did it affect your interest?",1500)}{field("nextStep","what would you like to explore next?",1000)}</>}
 <div className="detail-actions"><button className="button secondary" disabled={step===0} onClick={()=>setStep(s=>s-1)}>Previous prompt</button>{step<4?<button className="button primary" onClick={()=>setStep(s=>s+1)}>Next prompt</button>:<button className="button primary" disabled={!experience.whatDid.trim()} onClick={()=>{update({reflectionCompletedAt:todayISO()});setOpen(false);toast("Reflection notes saved. Your Exploration Map uses these notes.");}}>Finish reflection</button>}{step===4&&<button className="inline-link" onClick={()=>navigate("evidence")}>See my evidence</button>}</div></details>;
}
