"use client";
import { useState, useEffect } from "react";
import { Plus, ExternalLink, Download, Leaf, Trash2, Check, CalendarDays, ArrowLeft } from "lucide-react";
import { statuses, recordDeadline, dateLabel, deadlineLabel, daysUntil,todayISO, type TrackedRecord } from "@/lib/domain";
import { useWorkspace } from "./workspace-context";
import { Heading, Empty, Field, Notice, safeHref, download, csv } from "./shared";
import { ApplicationWorkspace } from "./application-workspace";
import { intentions } from "@/lib/domain";
import { deadlineIntelligence } from "@/lib/intelligence";
import { reminderKinds } from "@/lib/workspace-events";
import { SourceBadge } from "./opportunity";

export function Tracker(){
 const {data,navigate,activeRecord,setActiveRecord,startImport,updateRecord,removeRecord,startExperience}=useWorkspace();
 const [intent,setIntent]=useState(data.records.some(r=>r.intent==="Applying")?"Applying":"All interests"),[filter,setFilter]=useState("All"),[sort,setSort]=useState("Next action"),[checklistText,setChecklistText]=useState(""),[reminderText,setReminderText]=useState(""),[reminderDate,setReminderDate]=useState("");
 const [reminderKind,setReminderKind]=useState<typeof reminderKinds[number]>("Personal");
 const [detailOpen,setDetailOpen]=useState(false),[taskOpen,setTaskOpen]=useState(false);
 useEffect(()=>{setDetailOpen(false);setTaskOpen(false);},[activeRecord]);
 const selected=data.records.find(r=>r.opportunity.id===activeRecord);
 const groups=["All","Needs action","Awaiting response","Completed",...statuses.filter(s=>s!=="Completed")];
 const visible=data.records.filter(r=>intent==="All interests"||r.intent===intent).filter(r=>filter==="All"||filter==="Needs action"&&["Saved","Researching","Preparing application","Interview / next stage","Accepted"].includes(r.status)||filter==="Awaiting response"&&["Applied","Interview / next stage"].includes(r.status)||r.status===filter).sort((a,b)=>{
  if(sort==="Deadline")return (recordDeadline(a)||"9999").localeCompare(recordDeadline(b)||"9999");
  if(sort==="Recently saved")return b.savedAt.localeCompare(a.savedAt);
  if(sort==="Priority"){const order={High:0,Normal:1,Low:2};return order[a.priority]-order[b.priority];}
  return (a.nextActionDate||recordDeadline(a)||"9999").localeCompare(b.nextActionDate||recordDeadline(b)||"9999");
 });
 function setStatus(record:TrackedRecord,status:TrackedRecord["status"]){
  updateRecord(record.opportunity.id,{status,...(["Preparing application","Applied","Interview / next stage","Accepted"].includes(status)?{intent:"Applying" as const}:{}),...(status==="Applied"&&!record.appliedAt?{appliedAt:todayISO()}:{})});
 }
 function exportRecords(){download("sixthstep-opportunities.csv",csv([["Title","Provider","Status","Priority","Deadline","Next action","Action due","Date saved","Date applied","Event date","Outcome","Application URL","Notes","Checklist","Reminders"],...data.records.map(r=>[r.opportunity.title,r.opportunity.provider,r.status,r.priority,recordDeadline(r)||r.opportunity.deadline,r.nextAction,r.nextActionDate,r.savedAt,r.appliedAt,r.eventDate,r.outcome,r.applicationUrl,r.notes,r.checklist.map(c=>(c.done?"Done: ":"To do: ")+c.label).join("; "),r.reminders.map(c=>(c.done?"Done: ":"To do: ")+c.label+" "+c.date).join("; ")])]),"text/csv");}
 const update=(patch:Partial<TrackedRecord>)=>{if(selected)updateRecord(selected.opportunity.id,patch);};
 return <><Heading eyebrow="MAKE THE NEXT STEP HAPPEN" title="Your opportunity workspace." description="Keep applications, actions and deadlines together. Reminders appear here when you return." action={<button className="button primary" onClick={()=>startImport()}><Plus size={16}/>Add opportunity</button>}/>
 <div className="feature-toolbar"><label className="sr-only" htmlFor="intent-filter">Interest view</label><select id="intent-filter" className="text-input compact-select" value={intent} onChange={e=>setIntent(e.target.value)}><option>All interests</option>{intentions.map(i=><option key={i}>{i}</option>)}</select><label className="sr-only" htmlFor="tracker-filter">Tracker view</label><select id="tracker-filter" className="text-input compact-select" value={filter} onChange={e=>setFilter(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select><label className="sr-only" htmlFor="tracker-sort">Sort tracker</label><select id="tracker-sort" className="text-input compact-select" value={sort} onChange={e=>setSort(e.target.value)}>{["Next action","Deadline","Recently saved","Priority"].map(s=><option key={s}>{s}</option>)}</select><button className="button secondary" disabled={!data.records.length} onClick={exportRecords}><Download size={15}/>Export CSV</button></div>
 {selected?<section className="workspace-card tracker-detail"><button className="button text-button" onClick={()=>setActiveRecord("")}><ArrowLeft size={15}/>All my opportunities</button><div className="detail-title"><div><SourceBadge item={selected.opportunity}/><p className="provider-name">{selected.opportunity.provider}</p><h2>{selected.opportunity.title}</h2></div>{safeHref(selected.applicationUrl||selected.opportunity.url)&&<a className="button primary" href={safeHref(selected.applicationUrl||selected.opportunity.url)} target="_blank" rel="noreferrer">Provider / application page <ExternalLink size={15}/></a>}</div>
 <p className="card-intro">{selected.opportunity.description}</p><Notice>{selected.opportunity.eligibility} · Saved {dateLabel(selected.savedAt.slice(0,10))}</Notice>
 <Field label="Interest level"><select className="text-input compact-select" value={selected.intent} onChange={e=>update({intent:e.target.value as TrackedRecord["intent"]})}>{intentions.map(i=><option key={i}>{i}</option>)}</select></Field><div className="form-grid"><Field label={"Application status for "+selected.opportunity.title}><select className="text-input" value={selected.status} onChange={e=>setStatus(selected,e.target.value as TrackedRecord["status"])}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Priority"><select className="text-input" value={selected.priority} onChange={e=>update({priority:e.target.value as TrackedRecord["priority"]})}><option>Normal</option><option>High</option><option>Low</option></select></Field>
 <Field label="Next action"><input className="text-input" maxLength={300} placeholder="e.g. Ask my teacher for a reference" value={selected.nextAction} onChange={e=>update({nextAction:e.target.value})}/></Field><Field label="Next-action due date"><input className="text-input" type="date" value={selected.nextActionDate} onChange={e=>update({nextActionDate:e.target.value})}/></Field>
 </div><div className="application-overview"><p><strong>Stage:</strong> {selected.status} · <strong>Due:</strong> {recordDeadline(selected)?dateLabel(recordDeadline(selected)):selected.opportunity.deadline} · {selected.deadlineOverride?"Student-entered date":"Provider source — check current details"}</p><p><strong>Needs doing:</strong> {selected.nextAction||selected.requirements.find(r=>!r.done)?.label||selected.questions.find(q=>q.status==="Draft")?.question||"Check the provider requirements and choose your next action"}</p><p><strong>Outstanding:</strong> {selected.requirements.filter(r=>!r.done).length} confirmed requirements · {selected.questions.filter(q=>q.status==="Draft").length} draft answers</p><div className="detail-actions"><button className="button secondary" onClick={()=>{setDetailOpen(true);requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('.deadline-editor')?.previousElementSibling?.querySelector('input')?.focus());}}>Add / change deadline</button><button className="button secondary" onClick={()=>setTaskOpen(true)}>Add a task or reminder</button></div><ul className="task-list">{selected.requirements.filter(r=>!r.done).slice(0,3).map(r=><li key={r.id}><label><input type="checkbox" checked={r.done} onChange={()=>update({requirements:selected.requirements.map(t=>t.id===r.id?{...t,done:true}:t)})}/>Complete: {r.label}</label></li>)}</ul></div><details className="workspace-section" open={detailOpen} onToggle={e=>setDetailOpen(e.currentTarget.open)}><summary>Dates, links & outcome</summary><div className="form-grid"><Field label="Application deadline" hint="Enter or correct a date. Leave blank to remove the countdown."><input className="text-input" type="date" value={recordDeadline(selected)} onChange={e=>update({deadlineDate:e.target.value,deadlineOverride:true})}/></Field><div className="deadline-editor"><p className="field-label">Deadline context</p><p>{deadlineLabel(recordDeadline(selected),selected.opportunity.deadline)}</p><p className="fine-print">{deadlineIntelligence(selected.opportunity).kind}{deadlineIntelligence(selected.opportunity).stale?" · Possibly stale source":""}</p>{selected.deadlineOverride&&<p className="fine-print">Student-entered override · original source deadline: {selected.opportunity.deadlineDate||selected.opportunity.deadline}</p>}{selected.deadlineOverride&&<button className="inline-link" onClick={()=>update({deadlineOverride:false})}>Use source deadline again</button>}</div>
 <Field label="Application URL" hint="A public HTTPS link"><input className="text-input" type="url" maxLength={2000} value={selected.applicationUrl} onChange={e=>update({applicationUrl:e.target.value})}/></Field><Field label="Date applied"><input className="text-input" type="date" value={selected.appliedAt} onChange={e=>update({appliedAt:e.target.value})}/></Field>
 <Field label="Interview / event date"><input className="text-input" type="date" value={selected.eventDate} onChange={e=>update({eventDate:e.target.value})}/></Field><Field label="Outcome"><input className="text-input" maxLength={1000} placeholder="e.g. Waiting for a reply" value={selected.outcome} onChange={e=>update({outcome:e.target.value})}/></Field></div>
 <Field label="My notes"><textarea className="large-textarea short-textarea" maxLength={6000} value={selected.notes} onChange={e=>update({notes:e.target.value})} placeholder="Questions to ask, application ideas, travel plans…"/></Field></details>
 <details className="workspace-section" open={taskOpen} onToggle={e=>setTaskOpen(e.currentTarget.open)}><summary>Personal checklist & reminders</summary><div className="form-grid"><section><h3>Application checklist</h3><p className="fine-print">Add only documents or tasks your provider requires.</p><ul className="task-list">{selected.checklist.map(c=><li key={c.id}><label><input type="checkbox" checked={c.done} onChange={()=>update({checklist:selected.checklist.map(v=>v.id===c.id?{...v,done:!v.done}:v)})}/><span>{c.label}</span></label><button className="icon-button" aria-label={"Remove checklist item "+c.label} onClick={()=>update({checklist:selected.checklist.filter(v=>v.id!==c.id)})}><XIcon/></button></li>)}</ul><form className="inline-form" onSubmit={e=>{e.preventDefault();if(checklistText.trim()&&selected.checklist.length<40){update({checklist:[...selected.checklist,{id:crypto.randomUUID(),label:checklistText.trim(),done:false}]});setChecklistText("");}}}><input aria-label="New checklist item" className="text-input" maxLength={250} value={checklistText} onChange={e=>setChecklistText(e.target.value)} placeholder="e.g. Teacher reference"/><button className="button secondary" disabled={!checklistText.trim()||selected.checklist.length>=40}>Add</button></form></section>
 <section><h3>My reminders</h3><p className="fine-print">Shown in your dashboard. No emails or background notifications.</p><ul className="task-list">{selected.reminders.map(r=><li key={r.id}><label><input type="checkbox" checked={r.done} onChange={()=>update({reminders:selected.reminders.map(v=>v.id===r.id?{...v,done:!v.done}:v)})}/><span>{r.label}<small>{r.kind} · {dateLabel(r.date)}{(daysUntil(r.date)??0)<0?" · Overdue":""}</small></span></label><button className="icon-button" aria-label={"Remove reminder "+r.label} onClick={()=>update({reminders:selected.reminders.filter(v=>v.id!==r.id)})}><XIcon/></button></li>)}</ul><form onSubmit={e=>{e.preventDefault();if(reminderText.trim()&&reminderDate&&selected.reminders.length<30){update({reminders:[...selected.reminders,{id:crypto.randomUUID(),label:reminderText.trim(),date:reminderDate,done:false,kind:reminderKind}]});setReminderText("");setReminderDate("");}}}><Field label="Reminder type"><select className="text-input" value={reminderKind} onChange={e=>setReminderKind(e.target.value as typeof reminderKinds[number])}>{reminderKinds.map(k=><option key={k}>{k}</option>)}</select></Field><Field label="Reminder text"><input className="text-input" maxLength={250} value={reminderText} onChange={e=>setReminderText(e.target.value)} placeholder="e.g. Prepare questions"/></Field><div className="inline-form"><input aria-label="Reminder date" className="text-input" type="date" required value={reminderDate} onChange={e=>setReminderDate(e.target.value)}/><button className="button secondary" disabled={!reminderText.trim()||!reminderDate||selected.reminders.length>=30}>Add reminder</button></div></form></section></div></details>
 <ApplicationWorkspace key={selected.opportunity.id} record={selected}/><div className="detail-actions"><button className="button primary" onClick={()=>{setStatus(selected,"Completed");startExperience({...selected,status:"Completed"});}}><Leaf size={16}/>{selected.status==="Completed"?"Record / edit experience":"Mark completed & record experience"}</button><button className="button text-button danger" onClick={()=>{if(window.confirm("Remove this opportunity and its application notes? Existing journal entries will be kept.")){removeRecord(selected.opportunity.id);setActiveRecord("");}}}><Trash2 size={15}/>Remove opportunity</button></div><p className="fine-print">Your edits save automatically in this browser. Export a backup in your profile to keep the whole workspace.</p></section>:!data.records.length?<Empty title="Make room for your next possibility." action={()=>navigate("finder")} label="Find one opportunity">Save a programme from the finder or paste one you have already found. Then plan your next action.</Empty>:!visible.length?<Empty title="Nothing in this stage yet." action={()=>{setFilter("All");setIntent("All interests");}} label="Show all my opportunities">Choose another view or move an opportunity into this stage.</Empty>:<div className="tracked-list">{visible.map(record=><article className="workspace-card tracked-card" key={record.opportunity.id}><div><SourceBadge item={record.opportunity}/><p className="provider-name">{record.opportunity.provider}</p><button className="plain-title" onClick={()=>setActiveRecord(record.opportunity.id)}>{record.opportunity.title}</button><p className="intent-badge">{record.intent}</p><p className="fine-print">{record.nextAction||(["Applied","Interview / next stage"].includes(record.status)?"Waiting for next stage / response":"Choose your next action")}</p>{record.nextActionDate&&<p className={"deadline-note "+((daysUntil(record.nextActionDate)??0)<0?"past":"")}>Action {dateLabel(record.nextActionDate)}{(daysUntil(record.nextActionDate)??0)<0?" · Overdue":""}</p>}{recordDeadline(record)&&<p className="deadline-note">{deadlineLabel(recordDeadline(record))}</p>}</div><div className="tracked-controls"><label className="sr-only" htmlFor={"status-"+record.opportunity.id}>Application status for {record.opportunity.title}</label><select id={"status-"+record.opportunity.id} className="text-input" value={record.status} onChange={e=>setStatus(record,e.target.value as TrackedRecord["status"])}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="button secondary" onClick={()=>setActiveRecord(record.opportunity.id)}>Open workspace</button>{record.status==="Completed"&&<button className="button text-button" onClick={()=>startExperience(record)}><Leaf size={14}/>Record experience</button>}</div></article>)}</div>}
 </>;
}
function XIcon(){return <span aria-hidden="true">×</span>;}
