import { test, expect, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { appSchema, enrich, createRecord, experienceSchema, defaultProfile, questionSchema } from "../lib/domain";
const opportunity=enrich({id:"app",title:"Engineering insight application",provider:"Example University",sector:"Engineering",format:"Virtual",category:"Employer insight",source:"catalogue",sourceKind:"Programme",checkedAt:"2026-10-03",years:["Year 12"],minAge:16,maxAge:18,deadlineDate:"2026-10-09",deadline:"9 October 2026",url:"https://example.ac.uk/insight",applicationState:"Open"});
const second=enrich({...opportunity,id:"second",title:"Research programme",category:"Research placement",duration:"2 weeks",durationBand:"1–2 weeks"});
const entry=experienceSchema.parse({id:"journal",name:"Design simulation",careerAreas:["Engineering"],date:"2026-09-20",whatDid:"I compared two designs and explained my choice based on their cost.",enjoyed:"Comparing different designs",interestChange:"Increased",updatedAt:"2026-10-03",skills:[{id:"problem",skill:"Problem solving",whatHappened:"Two designs had different costs.",action:"I compared the costs and explained my choice.",learning:"Trade-offs matter."}]});
async function setup(page:Page,records=[createRecord(opportunity)],experiences=[entry]){
 await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/,r=>r.abort());
 await page.clock.setFixedTime(new Date("2026-10-03T12:00:00Z"));
 const data=appSchema.parse({version:2,profile:{...defaultProfile,configured:true,age:"17",subjects:["Maths","Physics"],interests:["Engineering"],careerInterests:"Engineering"},records,experiences});
 await page.addInitScript(value=>{if(!localStorage.getItem("sixthstep-workspace-v2"))localStorage.setItem("sixthstep-workspace-v2",JSON.stringify(value));},data);await page.goto("/");
}
async function nav(page:Page,name:string){if(await page.getByRole("button",{name:"Open menu",exact:true}).isVisible())await page.getByRole("button",{name:"Open menu",exact:true}).click();await page.locator(".sidebar").getByRole("button",{name:new RegExp("^"+name+"(?: \\d+)?$")}).click();}
async function draftContains(page:Page,text:string){await expect.poll(()=>page.getByLabel("Draft response",{exact:false}).inputValue()).toContain(text);}
async function workspace(page:Page){await nav(page,"Applications");await page.getByRole("button",{name:"Open workspace",exact:true}).first().click();}
test("shortlist, compare, choose, confirmed requirements, question suggestions and answer persistence form one journey",async({page})=>{
 const first={...createRecord(opportunity),intent:"Shortlisted" as const},other={...createRecord(second),intent:"Shortlisted" as const};await setup(page,[first,other]);await nav(page,"Explore");await page.getByRole("button",{name:"My shortlist",exact:true}).click();
 await page.getByLabel("Compare Engineering insight application",{exact:true}).check();await page.getByLabel("Compare Research programme",{exact:true}).check();await page.getByRole("button",{name:"Compare shortlist",exact:true}).click();
 const dialog=page.getByRole("dialog");await expect(dialog.getByRole("columnheader")).toHaveCount(3);await expect(dialog.locator(".comparison-difference")).not.toHaveCount(0);await expect(dialog.getByRole("rowheader",{name:"Selection process",exact:true})).toBeVisible();await page.keyboard.press("Escape");
 await page.getByRole("button",{name:"Choose to apply",exact:true}).first().click();await expect(page.getByLabel("Interest level",{exact:true})).toHaveValue("Applying");await expect(page.getByLabel("Application status for Engineering insight application")).toHaveValue("Preparing application");
 await page.getByText("Application requirements",{exact:true}).click();await expect(page.getByLabel("Teacher reference required",{exact:true})).toHaveCount(0);await page.getByLabel("Confirmed requirement",{exact:true}).selectOption("Teacher reference required");await page.getByRole("button",{name:"Add confirmed requirement",exact:true}).click();await expect(page.getByLabel("Teacher reference required",{exact:true})).not.toBeChecked();
 await page.getByLabel("New application question").fill("Tell us about a difficult problem you solved.");await page.getByRole("button",{name:"Add question",exact:true}).click();await page.getByText("Answer settings & limits",{exact:true}).click();await page.getByLabel("Limit type").selectOption("Words");await page.getByLabel("Response limit").fill("10");
 await expect(page.getByText("Potential evidence from your experience",{exact:true})).toBeVisible();await page.locator(".evidence-suggestion").getByText("Design simulation — Problem solving",{exact:true}).click();await expect(page.locator(".evidence-suggestion")).toContainText(entry.skills[0].action);
 await page.getByRole("button",{name:"Build STAR response",exact:true}).click();await draftContains(page,"Result: [Add your own detail]");await expect(page.getByRole("status").filter({hasText:"Over the stated limit"})).toBeVisible();
 await page.getByLabel("Response completion").selectOption("Ready");await expect(page.getByRole("alert").filter({hasText:"within its stated limit"})).toBeVisible();await page.getByLabel("Response limit").fill("200");await page.getByLabel("Response completion").selectOption("Ready");
 await page.reload();await page.getByRole("button",{name:"Open workspace",exact:true}).first().click();await draftContains(page,entry.skills[0].action);await expect(page.getByLabel("Response completion")).toHaveValue("Ready");await page.getByText("Evidence used in this draft",{exact:true}).click();await expect(page.getByText("Design simulation — Problem solving",{exact:true}).last()).toBeVisible();
 const download=page.waitForEvent("download");await page.getByRole("button",{name:"Export answer",exact:true}).click();expect((await download).suggestedFilename()).toBe("sixthstep-answer.txt");
});
test("evidence can create an interview draft and backup restore retains questions and source links",async({page})=>{
 await setup(page);await nav(page,"Evidence");await page.getByRole("button",{name:"Use for interview preparation",exact:true}).click();await page.getByLabel("Question to prepare").fill("How did you solve a problem?");await page.getByLabel("Use a STAR structure",{exact:false}).check();await page.getByRole("button",{name:"Copy to selected draft",exact:true}).click();
 await expect(page.getByLabel("Response purpose")).toHaveValue("Interview");await expect(page.getByLabel("Question text")).toHaveValue("How did you solve a problem?");await draftContains(page,entry.skills[0].action);
 await nav(page,"Profile");const pending=page.waitForEvent("download");await page.getByRole("button",{name:"Export workspace backup",exact:true}).click();const download=await pending,path=await download.path();const backup=await readFile(path!,"utf8");const parsed=JSON.parse(backup);expect(parsed.records[0].questions[0].evidenceIds).toEqual(["journal::problem"]);
 await page.evaluate(()=>localStorage.removeItem("sixthstep-workspace-v2"));await page.reload();await page.getByLabel("Restore workspace backup").setInputFiles({name:"backup.json",mimeType:"application/json",buffer:Buffer.from(backup)});await page.getByRole("button",{name:"Restore this workspace",exact:true}).click();await workspace(page);await page.getByLabel("Select question").selectOption(parsed.records[0].questions[0].id);await draftContains(page,entry.skills[0].action);
});
test("completed opportunity guides reflection into evidence and the Exploration Map without AI",async({page})=>{
 await setup(page,[createRecord(opportunity)],[]);await workspace(page);await page.getByRole("button",{name:"Mark completed & record experience",exact:true}).click();await expect(page.getByText("Short guided reflection",{exact:true})).toBeVisible();
 await page.getByLabel("Reflection: what did you personally do?").fill("I compared two design options and explained the difference to the group.");await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: most interesting or enjoyable part").fill("Comparing design trade-offs");await page.getByLabel("Reflection: what interested you less").fill("Repeating the same calculations");await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: what did you learn?").fill("Explain why a design meets the constraints.");await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: situation for this example").fill("Two design options for a group task");await page.getByLabel("Reflection: specific action that proves it").fill("I compared the designs against the stated constraints.");await page.getByRole("button",{name:"Keep this evidence example",exact:true}).click();await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: career area for grouping").selectOption("Engineering");await page.getByLabel("Reflection: change in career interest").selectOption("Increased");await page.getByLabel("Reflection: how did it affect your interest?").fill("I want to explore engineering design further.");await page.getByRole("button",{name:"Finish reflection",exact:true}).click();
 await page.getByRole("button",{name:"Exploration Map",exact:true}).click();await expect(page.locator(".map-quote").filter({hasText:"Comparing design trade-offs"})).toBeVisible();await expect(page.locator(".map-quote").filter({hasText:"Repeating the same calculations"})).toBeVisible();await expect(page.getByText("Suggested adjacent areas to explore",{exact:true})).toBeVisible();await nav(page,"Evidence");await expect(page.getByText("I compared the designs against the stated constraints.",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Use for application",exact:true}).click();await expect(page.getByRole("dialog")).toContainText("Save an opportunity first");
});
test("deadline alerts are useful, dismissible, persistent and show manual source overrides",async({page})=>{
 const record=createRecord(opportunity);record.nextAction="Finish motivation answer";record.nextActionDate="2026-10-02";record.intent="Applying";await setup(page,[record],[]);await page.getByText(/Source checks & other alerts \(/).click();await expect(page.getByText("Next action is overdue",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Dismiss alert: Next action is overdue",exact:true}).click();await page.reload();await expect(page.getByText("Next action is overdue",{exact:true})).toHaveCount(0);
 await workspace(page);await page.getByRole("button",{name:"Add / change deadline",exact:true}).click();await page.getByLabel("Application deadline",{exact:false}).fill("2026-10-04");await expect(page.getByText(/Student-entered override · original source deadline/)).toContainText("2026-10-09");await nav(page,"Home");await page.getByText(/Source checks & other alerts \(/).click();await expect(page.getByText("Closing tomorrow",{exact:true})).toBeVisible();await expect(page.getByText("Deadline changed manually",{exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Evidence readiness",exact:true})).toBeVisible();
});
test("mobile application answers, evidence reuse and exploration remain keyboard accessible without overflow",async({page})=>{
 await page.setViewportSize({width:390,height:844});const record=createRecord(opportunity);record.questions=[questionSchema.parse({id:"q",question:"Describe a difficult problem."})];await setup(page,[record]);await workspace(page);await expect(page.getByLabel("Application deadline",{exact:false})).not.toBeVisible();await page.getByText("Dates, links & outcome",{exact:true}).click();await page.getByLabel("Application deadline",{exact:false}).fill("2026-10-11");await page.getByText("Dates, links & outcome",{exact:true}).click();await page.getByLabel("Draft response",{exact:false}).fill("I compared the costs of two designs.");
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:"test-results/application-mobile.png",fullPage:true});
 await nav(page,"Evidence");await page.getByRole("button",{name:"Use for application",exact:true}).click();await expect(page.getByRole("dialog")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.getByLabel("Destination question").selectOption("q");await page.getByRole("button",{name:"Copy to selected draft",exact:true}).click();await draftContains(page,"I compared the costs of two designs.");await draftContains(page,entry.skills[0].action);
 await nav(page,"Experiences");await page.getByRole("button",{name:"Exploration Map",exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:"test-results/exploration-mobile.png",fullPage:true});await page.getByRole("button",{name:"Open menu",exact:true}).click();await page.keyboard.press("Escape");await expect(page.getByRole("button",{name:"Open menu",exact:true})).toBeFocused();
});
test("published-band filtering does not declare unknown eligibility confirmed and stale sources remain explicit",async({page})=>{
 await setup(page);await nav(page,"Explore");await page.getByLabel("Published age/year fit",{exact:true}).check();await expect(page.getByText(/It does not confirm grades, geography or access criteria/)).toBeVisible();await page.getByRole("button",{name:/^Filters(?: \(\d+\))?$/}).click();await page.getByLabel("Age eligibility",{exact:false}).selectOption("17");await page.getByLabel("School year",{exact:true}).selectOption("Year 12");
 for(const card of await page.locator(".opportunity-card").all())await expect(card.locator(".opportunity-facts")).not.toContainText("Age not stated");
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem("sixthstep-workspace-v2")!));stored.records[0].opportunity.checkedAt="2026-01-01";stored.records[0].opportunity.deadlineDate="";stored.records[0].opportunity.deadline="Not stated";await page.evaluate(value=>localStorage.setItem("sixthstep-workspace-v2",JSON.stringify(value)),stored);await page.reload();await workspace(page);await page.getByRole("button",{name:"Add / change deadline",exact:true}).click();await expect(page.getByText(/Possibly stale source/)).toBeVisible();await expect(page.getByLabel("Application deadline",{exact:false})).toHaveValue("");
});
