import { test, expect, type Page } from "@playwright/test";
import { appSchema, emptyData, enrich, createRecord, experienceSchema } from "../lib/domain";
const opportunity=enrich({id:"operating",title:"Engineering opportunity",provider:"Example University",sector:"Engineering",subjects:["Physics","Maths"],years:["Year 12"],source:"catalogue",checkedAt:"2026-10-03",category:"Employer insight",format:"Virtual",openingDate:"2026-10-03",deadlineDate:"2026-10-09",startDate:"2026-11-05",deadline:"9 October 2026",url:"https://example.ac.uk/engineering",applicationState:"Open"});
const profile={...emptyData.profile,configured:true,subjects:["Physics","Maths"],interests:["Engineering"],careerInterests:"Engineering"};
async function nav(page:Page,name:string){if(await page.getByRole("button",{name:"Open menu",exact:true}).isVisible())await page.getByRole("button",{name:"Open menu",exact:true}).click();await page.locator(".sidebar").getByRole("button",{name:new RegExp("^"+name+"(?: \\d+)?$")}).click();}
async function setup(page:Page,records=[createRecord(opportunity)],experiences:ReturnType<typeof experienceSchema.parse>[]=[]){
 await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/,r=>r.abort());await page.clock.setFixedTime(new Date("2026-10-03T12:00:00Z"));
 const data=appSchema.parse({...emptyData,profile,records,experiences});
 await page.addInitScript(value=>{if(!localStorage.getItem("sixthstep-workspace-v2"))localStorage.setItem("sixthstep-workspace-v2",JSON.stringify(value));},data);await page.goto("/");
}
async function openWorkspace(page:Page){await nav(page,"Applications");await page.getByRole("button",{name:"Open workspace",exact:true}).first().click();}
test("minimal setup immediately gives explained opportunities, comparison and a clear plan",async({page})=>{
 await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/,r=>r.abort());await page.clock.setFixedTime(new Date("2026-10-03T12:00:00Z"));await page.goto("/");
 const setup=page.getByRole("region",{name:"Quick student setup"});await setup.getByLabel("Your school year").selectOption("Year 12");await setup.getByLabel("Subjects you study",{exact:false}).fill("Maths, Physics");await setup.getByRole("button",{name:"Continue",exact:true}).click();await setup.getByLabel("Broad interests",{exact:false}).fill("Engineering");await setup.getByLabel("Career areas you are considering",{exact:false}).fill("Engineering");await setup.getByRole("button",{name:"Continue",exact:true}).click();await setup.getByLabel("Preferred opportunity format").selectOption("Virtual");await setup.getByRole("button",{name:"Show my opportunities",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Opportunities to explore",exact:true})).toBeVisible();await expect(page.locator(".match-note").first()).toContainText(/interest|Physics|Maths/);
 const grid=page.locator(".opportunity-grid").last(),cards=grid.locator(".opportunity-card");
 await cards.nth(0).getByRole("button",{name:/^Compare /}).click();await cards.nth(1).getByRole("button",{name:/^Compare /}).click();await page.getByRole("button",{name:"Compare opportunities",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Save this shortlist",exact:true}).click();await page.keyboard.press("Escape");
 await nav(page,"Explore");await page.getByRole("button",{name:"My shortlist",exact:true}).click();await page.getByRole("button",{name:"Choose to apply",exact:true}).first().click();await expect(page.locator(".application-overview")).toContainText("Stage: Applying");await expect(page.getByLabel("My notes",{exact:true})).not.toBeVisible();
 await page.getByLabel("Next action",{exact:true}).fill("Ask teacher about eligibility");await page.getByLabel("Next-action due date").fill("2026-10-04");await nav(page,"Home");await expect(page.getByRole("region",{name:"Priority actions"})).toContainText("Ask teacher about eligibility");
 await nav(page,"Calendar");await expect(page.getByRole("article",{name:"Ask teacher about eligibility",exact:true})).toContainText("Student-entered date");await page.getByRole("article",{name:"Ask teacher about eligibility",exact:true}).getByRole("button",{name:"Open application",exact:true}).click();await expect(page.getByLabel("Next action",{exact:true})).toHaveValue("Ask teacher about eligibility");
});
test("feedback adapts discovery, survives reload and hidden opportunities can be restored",async({page})=>{
 await setup(page,[]);await nav(page,"Explore");await page.getByLabel("Search opportunities").fill("Leonardo");
 const card=page.locator(".opportunity-card").filter({hasText:"Inside the world of Leonardo"});await card.locator(".feedback-controls summary").click();await card.getByLabel("Feedback for Inside the world of Leonardo",{exact:true}).selectOption("Not for me");await expect(card).toHaveCount(0);
 await page.reload();await expect(page.locator(".opportunity-card").filter({hasText:"Inside the world of Leonardo"})).toHaveCount(0);await page.getByText(/Your discovery feedback \(/).click();await expect(page.locator(".feedback-history")).toContainText("Not for me");await page.getByRole("button",{name:"Reset feedback",exact:true}).click();await page.getByLabel("Search opportunities").fill("Leonardo");await expect(card).toBeVisible();
 await card.locator(".feedback-controls summary").click();await card.getByLabel("Feedback for Inside the world of Leonardo",{exact:true}).selectOption("Show me more like this");await page.getByRole("button",{name:"Clear search",exact:true}).click();await expect(page.locator(".match-note").filter({hasText:"asked for more"}).first()).toBeVisible();
});
test("ranked Home actions support snoozing, persistence, recovery and explicit task completion",async({page})=>{
 const r=createRecord(opportunity);r.intent="Applying";r.nextAction="Ask my teacher";r.nextActionDate="2026-10-02";await setup(page,[r]);
 const action=page.getByRole("region",{name:"Priority actions"}).getByRole("article",{name:"Ask my teacher",exact:true});await expect(action).toContainText("Overdue");await action.getByRole("button",{name:"Reminder options",exact:true}).click();await action.getByLabel("Reminder date for Ask my teacher").fill("2026-10-06");await action.getByRole("button",{name:"Snooze / change reminder date",exact:true}).click();await expect(page.getByRole("region",{name:"Priority actions"}).getByRole("article",{name:"Ask my teacher",exact:true})).toHaveCount(0);await page.reload();await expect(page.getByRole("region",{name:"Priority actions"}).getByRole("article",{name:"Ask my teacher",exact:true})).toHaveCount(0);
 await nav(page,"Calendar");await page.getByText("Reminder history & recovery",{exact:true}).click();await page.getByRole("button",{name:"Bring back today",exact:true}).click();await nav(page,"Home");await action.getByRole("button",{name:"Reminder options",exact:true}).click();await action.getByRole("button",{name:"Mark complete",exact:true}).click();await expect(action).toHaveCount(0);await openWorkspace(page);await expect(page.getByLabel("Next action",{exact:true})).toHaveValue("");await expect(page.getByLabel("Application status for Engineering opportunity")).toHaveValue("Saved");
});
test("calendar combines opening, closing, interview and programme dates without scheduling vague windows",async({page})=>{
 const r=createRecord(opportunity),interview=createRecord(enrich({...opportunity,id:"interview",title:"Research interview",openingDate:"",startDate:""}));interview.status="Interview / next stage";interview.eventDate="2026-10-07";
 const vague=createRecord(enrich({...opportunity,id:"vague",title:"Unknown cycle",deadlineDate:"",openingDate:"",startDate:"",openingPeriod:"Autumn 2026",deadline:"Not announced"}));await setup(page,[r,interview,vague]);
 await nav(page,"Calendar");await expect(page.getByRole("article",{name:"Applications open: Engineering opportunity",exact:true})).toContainText("Confirmed source date");await expect(page.getByRole("article",{name:"Interview / next stage: Research interview",exact:true})).toContainText("Student-entered date");await page.getByRole("button",{name:"Month",exact:true}).click();await page.getByLabel("Calendar month").fill("2026-10");await page.getByRole("button",{name:/^7 Oct 2026: /}).click();await expect(page.getByRole("article",{name:"Interview / next stage: Research interview",exact:true})).toBeVisible();await page.getByRole("article",{name:"Interview / next stage: Research interview",exact:true}).getByRole("button",{name:"Open application",exact:true}).click();await expect(page.getByLabel("Application status for Research interview")).toHaveValue("Interview / next stage");
 await nav(page,"Calendar");await page.getByText(/Approximate periods & undated items/).click();const unknown=page.getByRole("article",{name:"Check opening period: Unknown cycle",exact:true});await expect(unknown).toContainText("Autumn 2026");await expect(unknown).toContainText("Approximate period");await expect(unknown).not.toContainText(/\d+ days/);
});
test("completion, manual reflection, evidence retrieval, development history and pathways stay connected",async({page})=>{
 await setup(page);await openWorkspace(page);await expect(page.getByRole("button",{name:"Mark completed & record experience",exact:true})).toBeDisabled();await page.getByLabel(/^Application status for /).selectOption("Interview / next stage");await page.getByRole("button",{name:"Mark completed & record experience",exact:true}).click();
 await page.getByText("Short guided reflection",{exact:true}).click();await page.getByLabel("Reflection: what did you personally do?").fill("I compared two designs and explained how each met the constraints.");await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: most interesting or enjoyable part").fill("Comparing engineering designs");await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: what did you learn?").fill("State the evidence behind a design choice.");await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: situation for this example").fill("Two engineering designs");await page.getByLabel("Reflection: specific action that proves it").fill("I compared the constraints and explained my choice.");await page.getByRole("button",{name:"Keep this evidence example",exact:true}).click();await page.getByRole("button",{name:"Next prompt",exact:true}).click();await page.getByLabel("Reflection: change in career interest").selectOption("Increased");await page.getByRole("button",{name:"Finish reflection",exact:true}).click();
 if(!await page.getByRole("button",{name:"Development timeline",exact:true}).isVisible())await page.getByText("Explore your learning",{exact:true}).click();await page.getByRole("button",{name:"Development timeline",exact:true}).click();const timeline=page.getByRole("region",{name:"Development timeline"});await expect(timeline).toContainText("Completed programme");await expect(timeline).toContainText("Evidence added");await expect(timeline).toContainText("Reflection completed");await expect(timeline).toContainText("Interest changed");await timeline.getByRole("button",{name:"Open source experience",exact:true}).first().click();await expect(page.getByLabel("Experience name")).toHaveValue("Engineering opportunity");
 await nav(page,"Evidence");await page.getByLabel("Search evidence").fill("constraints");await expect(page.locator(".evidence-card")).toHaveCount(1);await expect(page.locator(".evidence-card")).toContainText("0 / 4 fields recorded");await expect(page.locator(".evidence-card")).toContainText("Not recorded — add your own result");
 await nav(page,"Experiences");if(!await page.getByRole("button",{name:"Exploration Map",exact:true}).isVisible())await page.getByText("Explore your learning",{exact:true}).click();await page.getByRole("button",{name:"Exploration Map",exact:true}).click();const path=page.getByRole("region",{name:"Pathway exploration"});await expect(path).toContainText("Mechanical engineering");await expect(path).toContainText("Degree apprenticeships");await path.getByLabel("Pathway starting area").selectOption("Medicine");await expect(path).toContainText("Pharmacy");await expect(path).toContainText("Health volunteering");await expect(path).toContainText("possibilities");await path.getByRole("button",{name:"Find more in this area",exact:true}).click();await page.getByRole("button",{name:/^Filters(?: \(\d+\))?$/}).click();await expect(page.getByRole("button",{name:"Healthcare",exact:true})).toHaveAttribute("aria-pressed","true");
});
test("first-use recovery and mobile calendar/development navigation have clear actions and no overflow",async({page})=>{
 await page.setViewportSize({width:390,height:844});await setup(page,[]);await nav(page,"Calendar");await expect(page.getByRole("heading",{name:"Start with one date worth remembering.",exact:true})).toBeVisible();await page.getByRole("button",{name:"Find an opportunity",exact:true}).click();await expect(page.getByLabel("Search opportunities")).toBeVisible();await nav(page,"Experiences");if(!await page.getByRole("button",{name:"Development timeline",exact:true}).isVisible())await page.getByText("Explore your learning",{exact:true}).click();await page.getByRole("button",{name:"Development timeline",exact:true}).click();await page.getByRole("button",{name:"Find an opportunity",exact:true}).click();await expect(page.getByLabel("Search opportunities")).toBeVisible();
 const r=createRecord(opportunity);await page.evaluate(record=>{const data=JSON.parse(localStorage.getItem("sixthstep-workspace-v2")!);data.records=[record];localStorage.setItem("sixthstep-workspace-v2",JSON.stringify(data));},r);await page.reload();await nav(page,"Calendar");await page.getByRole("button",{name:"Month",exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:"test-results/calendar-mobile.png",fullPage:true});await page.getByRole("button",{name:"Open menu",exact:true}).click();await page.keyboard.press("Escape");await expect(page.getByRole("button",{name:"Open menu",exact:true})).toBeFocused();await nav(page,"Experiences");if(!await page.getByRole("button",{name:"Development timeline",exact:true}).isVisible())await page.getByText("Explore your learning",{exact:true}).click();await page.getByRole("button",{name:"Development timeline",exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});
test("collection pagination limits visible results and retains search and feedback after navigation",async({page})=>{
 await setup(page,[]);await nav(page,"Explore");const grid=page.locator(".opportunity-grid").last();await expect(grid.locator(".opportunity-card")).toHaveCount(18);await page.getByRole("button",{name:"Next page",exact:true}).click();await expect(page.getByRole("navigation",{name:"Opportunity pages"})).toContainText("Page 2");await expect(grid.locator(".opportunity-card")).toHaveCount(18);await page.getByLabel("Search opportunities").fill("Bebras");await expect(grid.locator(".opportunity-card")).toHaveCount(1);await expect(grid).toContainText("6–19");await grid.getByRole("button",{name:"View details: UK Bebras computational thinking challenge",exact:true}).click();await expect(page.getByRole("dialog")).toContainText("Teacher or home-education registration");await expect(page.getByRole("dialog")).toContainText("Source recorded");await page.keyboard.press("Escape");
});
