import { test, expect, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { appSchema, emptyData, createRecord, enrich, questionSchema, experienceSchema, evidenceBank } from "../lib/domain";
import { linkEvidence } from "../lib/application-preparation";
const at="2026-10-03T12:00:00Z";
const opportunity=enrich({id:"durable",title:"Engineering insight with a deliberately long programme title for mobile review",provider:"Example University",source:"catalogue",checkedAt:"2026-10-03",sector:"Engineering",url:"https://example.ac.uk/insight",deadlineDate:"2026-10-09",deadline:"9 October 2026",startDate:"2026-11-05",openingPeriod:"Autumn 2026"});
const experience=experienceSchema.parse({id:"source",name:"Design exercise",type:"Work experience",careerAreas:["Engineering"],whatDid:"I compared two designs and explained the constraints.",updatedAt:at,skills:[{id:"problem",skill:"Problem solving",whatHappened:"A design exercise",action:"I compared two designs against the constraints.",learning:"Explain the tradeoff."}]});
const record=createRecord(opportunity,at);record.intent="Applying";record.nextAction="Ask my teacher";record.nextActionDate="2026-10-04";record.questions=[questionSchema.parse({id:"first",question:"Describe a difficult problem you solved and explain the personal action you took, the outcome and what you learned.",limitKind:"Words",limit:100}),questionSchema.parse({id:"second",question:"Why are you interested in engineering?",draft:"I enjoy comparing designs."})];
const data=appSchema.parse({...emptyData,profile:{...emptyData.profile,configured:true,subjects:["Physics"],interests:["Engineering"]},records:[record],experiences:[experience]});
async function setup(page:Page,hash="#saved/durable/questions/first",value=data){
 await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/,r=>r.abort());await page.clock.setFixedTime(new Date(at));
 await page.addInitScript(snapshot=>{if(!localStorage.getItem("sixthstep-workspace-v2"))localStorage.setItem("sixthstep-workspace-v2",JSON.stringify(snapshot));},value);await page.goto("/"+hash);
}
async function nav(page:Page,name:string){if(await page.getByRole("button",{name:"Open menu",exact:true}).isVisible())await page.getByRole("button",{name:"Open menu",exact:true}).click();await page.locator(".sidebar").getByRole("button",{name:new RegExp("^"+name+"(?: \\d+)?$")}).click();}
test("application and question addresses survive reload and browser back/forward",async({page})=>{
 await setup(page);await expect(page.getByLabel("Select question")).toHaveValue("first");await page.getByLabel("Draft response",{exact:false}).fill("My own first answer.");await page.getByLabel("Select question").selectOption("second");await expect(page).toHaveURL(/#saved\/durable\/questions\/second$/);await page.reload();await expect(page.getByLabel("Select question")).toHaveValue("second");await expect(page.getByLabel("Draft response",{exact:false})).toHaveValue("I enjoy comparing designs.");
 await page.goBack();await expect(page.getByLabel("Select question")).toHaveValue("first");await expect(page.getByLabel("Draft response",{exact:false})).toHaveValue("My own first answer.");await page.goForward();await expect(page.getByLabel("Select question")).toHaveValue("second");
});
test("opportunity, experience and evidence deep links reopen the same source and report missing records",async({page})=>{
 await setup(page,"#finder/opportunities/durable");await expect(page.getByRole("dialog")).toContainText(opportunity.title);await page.reload();await expect(page.getByRole("dialog")).toContainText(opportunity.title);await page.keyboard.press("Escape");await expect(page).toHaveURL(/#finder$/);
 await page.goto("/#reflect/source");await expect(page.getByLabel("Experience name")).toHaveValue(experience.name);await page.reload();await expect(page.getByLabel("What I did",{exact:true})).toHaveValue(experience.whatDid);
 await page.goto("/#evidence/source%3A%3Aproblem");await expect(page.locator(".evidence-card")).toHaveCount(1);await expect(page.locator(".evidence-card")).toBeFocused();await page.reload();await expect(page.locator(".evidence-card")).toContainText(experience.skills[0].action);
 await page.goto("/#saved/missing");await expect(page.getByRole("heading",{name:"This application is not in this browser.",exact:true})).toBeVisible();await page.getByRole("button",{name:"Return to my workspace",exact:true}).click();await expect(page.getByRole("button",{name:"Open workspace",exact:true})).toBeVisible();
});
test("individual and grouped calendar exports retain exact dates and omit approximate periods",async({page})=>{
 await setup(page,"#calendar");const item=page.getByRole("article",{name:"Ask my teacher",exact:true});const pending=page.waitForEvent("download");await item.getByRole("button",{name:"Export date",exact:true}).click();let file=await pending;let text=await readFile((await file.path())!,"utf8");expect(text).toContain("DTSTART;VALUE=DATE:20261004");expect(text.replace(/\r\n /g,"")).toContain("Student-entered date");expect(text).not.toContain("Autumn 2026");
 await page.getByText("Export to your calendar (.ics)",{exact:true}).click();await page.getByLabel("Deadline",{exact:true}).check();const group=page.waitForEvent("download");await page.getByRole("button",{name:"Export selected groups (1)",exact:true}).click();file=await group;text=await readFile((await file.path())!,"utf8");expect(text).toContain("DTSTART;VALUE=DATE:20261009");expect((text.match(/BEGIN:VEVENT/g)||[]).length).toBe(1);expect(text.replace(/\r\n /g,"")).toContain(opportunity.url);
});
test("another tab's changes are not silently overwritten and current edits can be recovered",async({page,context})=>{
 await setup(page);const other=await context.newPage();await other.goto("/#saved/durable/questions/first");await expect(other.getByLabel("Draft response",{exact:false})).toBeVisible();await page.getByLabel("Draft response",{exact:false}).fill("My first tab's answer.");
 await expect(other.getByRole("alert").filter({hasText:"Another tab changed"})).toBeVisible();await other.getByLabel("Draft response",{exact:false}).fill("My second tab's answer.");await expect(page.getByLabel("Draft response",{exact:false})).toHaveValue("My first tab's answer.");
 await other.getByRole("button",{name:"Keep this tab's version",exact:true}).click();await other.reload();await expect(other.getByLabel("Draft response",{exact:false})).toHaveValue("My second tab's answer.");const before=await other.evaluate(()=>JSON.parse(localStorage.getItem("sixthstep-before-replacement-v2")!));expect(before.records[0].questions[0].draft).toBe("My first tab's answer.");await other.close();
});
test("changed and removed evidence warns visibly while preserving the answer snapshot",async({page})=>{
 const value=structuredClone(data),bank=evidenceBank(value.experiences),q=value.records[0].questions[0];Object.assign(q,linkEvidence(q,bank[0]));q.draft="My own answer keeps the original wording.";value.experiences[0].skills[0].action="I edited the source action.";await setup(page,"#saved/durable/questions/first",value);
 await expect(page.getByRole("alert").filter({hasText:"Source evidence changed"})).toBeVisible();await expect(page.getByLabel("Draft response",{exact:false})).toHaveValue(q.draft);
 await page.evaluate(()=>{const saved=JSON.parse(localStorage.getItem("sixthstep-workspace-v2")!);saved.experiences=[];localStorage.setItem("sixthstep-workspace-v2",JSON.stringify(saved));});await page.reload();await expect(page.getByRole("alert").filter({hasText:"Source evidence was removed"})).toBeVisible();await expect(page.getByLabel("Draft response",{exact:false})).toHaveValue(q.draft);
});
test("copied evidence needs adaptation and empty or over-limit answers cannot be Ready",async({page})=>{
 await setup(page);await page.getByLabel("Response completion").selectOption("Ready");await expect(page.getByRole("alert").filter({hasText:"within its stated limit"})).toBeVisible();await page.locator(".evidence-suggestion summary").first().click();await page.getByRole("button",{name:"Build STAR response",exact:true}).click();await expect(page.getByLabel("Draft response",{exact:false})).toBeFocused();await page.getByLabel("Response completion").selectOption("Ready");await expect(page.getByRole("alert").filter({hasText:"missing evidence prompts"})).toBeVisible();await page.getByLabel("Draft response",{exact:false}).fill("I compared two designs and explained the tradeoff to my group.");await page.getByLabel("Response completion").selectOption("Ready");await expect(page.getByRole("alert").filter({hasText:"Review and adapt"})).toBeVisible();await page.getByLabel("I have reviewed and adapted this evidence",{exact:false}).check();await page.getByLabel("Response completion").selectOption("Ready");await expect(page.getByLabel("Response completion")).toHaveValue("Ready");
});
test("mobile workspaces at 360–430px retain keyboard focus, calm hierarchy and usable controls",async({page})=>{
 await setup(page);for(const width of [360,390,430]){await page.setViewportSize({width,height:844});await expect(page.getByLabel("Draft response",{exact:false})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await nav(page,"Evidence");await page.getByRole("button",{name:"Use for application",exact:true}).click();await expect(page.getByRole("dialog")).toBeVisible();await page.keyboard.press("Escape");await expect(page.getByRole("button",{name:"Use for application",exact:true})).toBeFocused();await nav(page,"Explore");await page.getByRole("button",{name:/^Filters(?: \(\d+\))?$/}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.getByRole("button",{name:/^Filters(?: \(\d+\))?$/}).click();const cards=page.locator(".opportunity-grid").last().locator(".opportunity-card");await cards.nth(0).getByRole("button",{name:/^Compare /}).click();await cards.nth(1).getByRole("button",{name:/^Compare /}).click();await page.getByRole("button",{name:"Compare opportunities",exact:true}).click();await expect(page.getByRole("dialog").getByRole("table")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);if(width===360)await page.screenshot({path:"test-results/comparison-final-mobile.png",fullPage:true});await page.keyboard.press("Escape");await nav(page,"Profile");expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await nav(page,"Calendar");await page.getByRole("button",{name:"Month",exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await nav(page,"Home");await expect(page.getByRole("region",{name:"Priority actions"})).toBeVisible();await expect(page.getByRole("heading",{name:"Evidence readiness",exact:true})).not.toBeVisible();await page.getByRole("link",{name:"Skip to content",exact:true}).focus();await page.keyboard.press("Enter");await expect(page.locator("#main-content")).toBeFocused();await expect(page).toHaveURL(/#dashboard$/);await nav(page,"Applications");}
 await page.screenshot({path:"test-results/workspace-final-mobile.png",fullPage:true});
});

test("saved work stays actionable before optional profile setup on mobile",async({page})=>{
 const value=structuredClone(data);value.profile.configured=false;
 await page.setViewportSize({width:390,height:844});await setup(page,"#dashboard",value);
 const priority=page.getByRole("region",{name:"Priority actions"});
 await expect(priority.getByRole("article",{name:"Ask my teacher",exact:true})).toBeVisible();
 await expect(page.getByRole("region",{name:"Quick student setup"})).not.toBeVisible();
 const bounds=await priority.boundingBox();expect(bounds?.y).toBeLessThan(400);
 await page.screenshot({path:"test-results/home-saved-work-mobile.png",fullPage:true});
 await page.getByText("Shape your discovery preferences",{exact:true}).click();
 await expect(page.getByRole("region",{name:"Quick student setup"})).toBeVisible();
});
