import { test, expect, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { createRecord, emptyData, enrich, experienceSchema, questionSchema } from "../lib/domain";

const opportunity=enrich({id:"weekly",title:"Engineering insight with a long programme title for mobile",provider:"Test university",source:"manual",format:"Virtual",deadlineDate:"2026-10-08",url:"https://example.org/programme"});
const record=createRecord(opportunity,"2026-10-03");record.intent="Applying";record.status="Preparing application";record.nextAction="Ask my teacher";record.nextActionDate="2026-10-02";record.requirements=[{id:"eligibility",label:"Check eligibility",note:"",done:false}];record.questions=[questionSchema.parse({id:"team",question:"Describe how you solved a problem in a team and what you personally learned.",limit:100,limitKind:"Words"})];
const experience=experienceSchema.parse({id:"experience",name:"Design simulation",whatDid:"I compared two designs and explained my choice to the group.",learned:"Explain the evidence behind a design decision.",updatedAt:"2026-10-03",skills:[{id:"problem",skill:"Problem solving",whatHappened:"Two designs needed comparing",action:"I compared their costs and explained my choice.",learning:"Consider trade-offs"}]});
const data={...structuredClone(emptyData),profile:{...emptyData.profile,configured:true,subjects:["Physics"],interests:["Engineering"]},records:[record],experiences:[experience]};
test.beforeEach(async({page})=>{await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/,r=>r.abort());await page.route("**/api/status",r=>r.fulfill({json:{ai:false,search:false,aiSetup:"missing"}}));await page.clock.setFixedTime(new Date("2026-10-03T12:00:00Z"));});
async function setup(page:Page,hash:string,value=data){await page.addInitScript(value=>{if(!localStorage.getItem("sixthstep-workspace-v2"))localStorage.setItem("sixthstep-workspace-v2",JSON.stringify(value));},value);await page.goto("/"+hash);await expect(page.getByRole("heading",{level:1})).toBeVisible();}
async function scan(page:Page){const result=await new AxeBuilder({page}).withTags(["wcag2a","wcag2aa","wcag21aa"]).analyze();expect(result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))).toEqual([]);}
for(const [view,hash] of [["Home","#dashboard"],["Explore","#finder"],["Applications","#saved/weekly/questions/team"],["Calendar","#calendar"],["Experiences","#reflect/experience"],["Evidence","#evidence"],["Profile","#settings"]]){
 test("mobile accessibility: "+view,async({page})=>{await page.setViewportSize({width:360,height:844});await setup(page,hash);if(view==="Explore")await page.getByRole("button",{name:"Filters",exact:true}).click();if(view==="Applications")await page.getByLabel("Draft response",{exact:false}).fill("I compared the designs and explained the trade-off.");await scan(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:"test-results/weekly-"+view.toLowerCase()+"-mobile.png",fullPage:true});});
}
test("Home shows work, upcoming dates and attention with direct routes",async({page})=>{
 await setup(page,"#dashboard");const priority=page.getByRole("region",{name:"Priority actions"});await expect(priority).toContainText("Ask my teacher");await expect(priority).not.toContainText("Take a look:");await expect(page.getByRole("heading",{name:"Possibilities to explore",exact:true})).toHaveCount(0);const upcoming=page.getByRole("region",{name:"Coming up"});await expect(upcoming).toContainText("8 Oct 2026");await expect(upcoming).toContainText("Student-entered date");const attention=page.getByRole("region",{name:"Needs attention"});await expect(attention).toContainText("overdue");await attention.getByRole("button").first().click();await expect(page).toHaveURL(/#saved\/weekly$/);await expect(page.getByLabel("Next action",{exact:true})).toHaveValue("Ask my teacher");
});
test("Explore defaults to one result list and feedback hides the exact opportunity",async({page})=>{
 await setup(page,"#finder");await expect(page.getByLabel("Opportunity type",{exact:true})).toHaveCount(0);await expect(page.locator(".filter-workspace")).toHaveCount(0);await expect(page.locator(".opportunity-grid")).toHaveCount(1);const card=page.locator(".opportunity-card").first(),title=await card.locator("h3").innerText();await card.locator(".feedback-controls summary").click();await card.getByLabel("Feedback for "+title,{exact:true}).selectOption("Not for me");await expect(page.getByRole("button",{name:title,exact:true})).toHaveCount(0);await page.reload();await expect(page.getByRole("button",{name:title,exact:true})).toHaveCount(0);await page.getByRole("button",{name:"Filters",exact:true}).click();await page.getByLabel("Opportunity type",{exact:true}).selectOption("Competition");await expect(page.locator(".opportunity-card")).not.toHaveCount(0);
});
test("reflection starts small and recorded evidence remains linked to its source",async({page})=>{
 await setup(page,"#reflect/experience");await expect(page.getByLabel("What I did",{exact:true})).toBeVisible();await expect(page.getByLabel("What I learned",{exact:true})).toBeVisible();await expect(page.getByLabel("What I enjoyed",{exact:true})).toBeVisible();await expect(page.getByLabel("Recorded change in career interest",{exact:true})).toBeVisible();await expect(page.getByLabel("Challenges I faced")).not.toBeVisible();await expect(page.getByRole("button",{name:"Help me reflect",exact:true})).not.toBeVisible();await page.getByLabel("What I enjoyed",{exact:true}).fill("Comparing the design options.");await page.getByLabel("Recorded change in career interest",{exact:true}).selectOption("Increased");await page.getByText("Capture a skill with evidence",{exact:true}).click();await page.getByLabel("Skill",{exact:true}).selectOption("Teamwork");await page.getByLabel("What I personally did",{exact:true}).fill("I invited each person to explain their design choice.");await page.getByRole("button",{name:"Add to evidence bank",exact:true}).click();await page.goto("/#evidence");const card=page.locator(".evidence-card").filter({hasText:"Teamwork"});await expect(card).toContainText("I invited each person");await card.getByRole("button",{name:"View / edit source experience",exact:true}).click();await expect(page.getByLabel("What I enjoyed",{exact:true})).toHaveValue("Comparing the design options.");
});
test("late web responses cannot replace a changed search and malformed responses explain the problem",async({page})=>{
 await page.route("**/api/status",r=>r.fulfill({json:{ai:false,search:true,aiSetup:"missing"}}));let release!:()=>void;await page.route("**/api/search",async r=>{await new Promise<void>(resolve=>{release=resolve;});await r.fulfill({json:{results:[{...opportunity,id:"late",title:"Obsolete web result"}],discarded:0}}).catch(()=>{});});await setup(page,"#finder");await page.getByLabel("Search opportunities").fill("engineering");await page.getByRole("button",{name:"Search the web",exact:true}).click();await expect.poll(()=>!!release).toBe(true);await page.getByLabel("Search opportunities").fill("physics");release();await expect(page.getByRole("button",{name:"Search the web",exact:true})).toBeEnabled();await expect(page.getByRole("button",{name:"Obsolete web result",exact:true})).toHaveCount(0);await page.unroute("**/api/search");await page.route("**/api/search",r=>r.fulfill({json:{results:{}}}));await page.getByRole("button",{name:"Search the web",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"unreadable results"})).toContainText("unreadable results");
});
test("fresh onboarding remains accessible on desktop and mobile with working skip navigation",async({page})=>{
 await setup(page,"#dashboard",{...data,...emptyData});for(const width of [1280,360]){await page.setViewportSize({width,height:900});await expect(page.getByRole("heading",{name:"Find one opportunity worth exploring.",exact:true})).toBeVisible();await scan(page);const skip=page.getByRole("link",{name:"Skip to content",exact:true});await skip.focus();await page.keyboard.press("Enter");await expect(page.locator("#main-content")).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);}
});
test("core reflection completion is explicit and does not require AI or deeper prompts",async({page})=>{
 await setup(page,"#reflect/experience");await page.getByRole("button",{name:"Save core reflection",exact:true}).click();await expect(page.getByText("Reflection recorded · 2026-10-03",{exact:true})).toBeVisible();await page.reload();await expect(page.getByText("Reflection recorded · 2026-10-03",{exact:true})).toBeVisible();await expect(page.getByLabel("What I did",{exact:true})).toHaveValue(experience.whatDid);await expect(page.getByRole("button",{name:"Help me reflect",exact:true})).not.toBeVisible();
});
test("opportunity dialog is accessible and Escape restores the triggering control",async({page})=>{
 await page.setViewportSize({width:390,height:844});await setup(page,"#finder");const trigger=page.locator(".card-title").first();await trigger.click();await expect(page.getByRole("dialog")).toBeVisible();await scan(page);await page.keyboard.press("Escape");await expect(trigger).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});
