import type { Opportunity } from "./types";
const checkedAt = "2026-10-02";
export const catalogue: Opportunity[] = [
  { id:"springpod-engineering", title:"Find your place in engineering", provider:"Springpod", sector:"Engineering", type:"Provider directory", location:"Virtual · UK", duration:"Varies by programme", eligibility:"Check each programme's age and region requirements", cost:"Check programme details", deadline:"Varies by programme", url:"https://www.springpod.com/virtual-work-experience/search", description:"Explore virtual work experience programmes and filter by engineering, organisation, age range and region on Springpod.", tags:["Engineering","Explore careers","Virtual"], checkedAt, source:"catalogue" },
  { id:"leonardo", title:"Inside the world of Leonardo", provider:"Leonardo · Springpod", sector:"Engineering", type:"Virtual experience", location:"Virtual", duration:"Not stated", eligibility:"Provider welcomes students of all ages; check current programme terms", cost:"Free", deadline:"Not stated", url:"https://www.leonardo.springpod.com/experiences/virtual-work-experience-with-leonardo", description:"Discover electronics, radar and aerospace careers through quizzes, practical activities and industry insights. Explore early career pathways and earn a completion certificate.", tags:["Aerospace","Electronics","Certificate"], checkedAt, source:"catalogue" },
  { id:"forage-tech", title:"Try a career in technology", provider:"Forage", sector:"Technology", type:"Provider directory", location:"Virtual · self-paced", duration:"Varies by simulation", eligibility:"Check the selected simulation and provider terms", cost:"Free", deadline:"Self-paced; check selected programme", url:"https://www.theforage.com/simulations", description:"Browse employer-designed job simulations in software engineering, cybersecurity, AI and data. Complete example workplace tasks at your own pace.", tags:["Coding","Cybersecurity","Job simulations"], checkedAt, source:"catalogue" },
  { id:"springpod-health", title:"Explore a future in healthcare", provider:"Springpod", sector:"Healthcare", type:"Provider directory", location:"Virtual · UK", duration:"Varies by programme", eligibility:"Check each programme's age and region requirements", cost:"Check programme details", deadline:"Varies by programme", url:"https://www.springpod.com/virtual-work-experience/search", description:"Find healthcare and medicine experiences. Use Springpod's sector and eligibility filters to choose a programme that fits your interests.", tags:["Healthcare","Medicine","Explore careers"], checkedAt, source:"catalogue" },
  { id:"forage-finance", title:"Step into business & finance", provider:"Forage", sector:"Business & finance", type:"Provider directory", location:"Virtual · self-paced", duration:"Varies by simulation", eligibility:"Check the selected simulation and provider terms", cost:"Free", deadline:"Self-paced; check selected programme", url:"https://www.theforage.com/simulations", description:"Discover banking, consulting and accounting job simulations. Work through employer-designed tasks and compare your work with example answers.", tags:["Finance","Consulting","Job simulations"], checkedAt, source:"catalogue" },
  { id:"forage-law", title:"See what a legal career looks like", provider:"Forage", sector:"Law", type:"Provider directory", location:"Virtual · self-paced", duration:"Varies by simulation", eligibility:"Check the selected simulation and provider terms", cost:"Free", deadline:"Self-paced; check selected programme", url:"https://www.theforage.com/simulations", description:"Explore law job simulations and practise tasks inspired by legal workplaces. A starting point for understanding different legal careers.", tags:["Law","Problem solving","Job simulations"], checkedAt, source:"catalogue" },
  { id:"springpod-creative", title:"Discover the creative industries", provider:"Springpod", sector:"Creative & media", type:"Provider directory", location:"Virtual · UK", duration:"Varies by programme", eligibility:"Check each programme's age and region requirements", cost:"Check programme details", deadline:"Varies by programme", url:"https://www.springpod.com/virtual-work-experience/search", description:"Browse experiences in media, marketing and creative careers, then check the dates and requirements on the provider's programme page.", tags:["Media","Marketing","Explore careers"], checkedAt, source:"catalogue" },
  { id:"springpod-tech", title:"Discover technology work experience", provider:"Springpod", sector:"Technology", type:"Provider directory", location:"Virtual · UK", duration:"Varies by programme", eligibility:"Check each programme's age and region requirements", cost:"Check programme details", deadline:"Varies by programme", url:"https://www.springpod.com/virtual-work-experience/search", description:"Explore technology programmes and discover workplace activities, industry talks and career pathways. Check the provider for current programmes.", tags:["Technology","Digital","Virtual"], checkedAt, source:"catalogue" }
];
